// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nekobot/pkg/toolsessions/ent/predicate"
	"nekobot/pkg/toolsessions/ent/toolevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ToolEventDelete is the builder for deleting a ToolEvent entity.
type ToolEventDelete struct {
	config
	hooks    []Hook
	mutation *ToolEventMutation
}

// Where appends a list predicates to the ToolEventDelete builder.
func (_d *ToolEventDelete) Where(ps ...predicate.ToolEvent) *ToolEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ToolEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ToolEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ToolEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(toolevent.Table, sqlgraph.NewFieldSpec(toolevent.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ToolEventDeleteOne is the builder for deleting a single ToolEvent entity.
type ToolEventDeleteOne struct {
	_d *ToolEventDelete
}

// Where appends a list predicates to the ToolEventDelete builder.
func (_d *ToolEventDeleteOne) Where(ps ...predicate.ToolEvent) *ToolEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ToolEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{toolevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ToolEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
