// Code generated by ent, DO NOT EDIT.

package provider

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the provider type in the database.
	Label = "provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProviderKind holds the string denoting the provider_kind field in the database.
	FieldProviderKind = "provider_kind"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldAPIBase holds the string denoting the api_base field in the database.
	FieldAPIBase = "api_base"
	// FieldProxy holds the string denoting the proxy field in the database.
	FieldProxy = "proxy"
	// FieldModelsJSON holds the string denoting the models_json field in the database.
	FieldModelsJSON = "models_json"
	// FieldDefaultModel holds the string denoting the default_model field in the database.
	FieldDefaultModel = "default_model"
	// FieldTimeout holds the string denoting the timeout field in the database.
	FieldTimeout = "timeout"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the provider in the database.
	Table = "providers"
)

// Columns holds all SQL columns for provider fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldProviderKind,
	FieldAPIKey,
	FieldAPIBase,
	FieldProxy,
	FieldModelsJSON,
	FieldDefaultModel,
	FieldTimeout,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ProviderKindValidator is a validator for the "provider_kind" field. It is called by the builders before save.
	ProviderKindValidator func(string) error
	// DefaultAPIKey holds the default value on creation for the "api_key" field.
	DefaultAPIKey string
	// DefaultAPIBase holds the default value on creation for the "api_base" field.
	DefaultAPIBase string
	// DefaultProxy holds the default value on creation for the "proxy" field.
	DefaultProxy string
	// DefaultModelsJSON holds the default value on creation for the "models_json" field.
	DefaultModelsJSON string
	// DefaultDefaultModel holds the default value on creation for the "default_model" field.
	DefaultDefaultModel string
	// DefaultTimeout holds the default value on creation for the "timeout" field.
	DefaultTimeout int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Provider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProviderKind orders the results by the provider_kind field.
func ByProviderKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKind, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByAPIBase orders the results by the api_base field.
func ByAPIBase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIBase, opts...).ToFunc()
}

// ByProxy orders the results by the proxy field.
func ByProxy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxy, opts...).ToFunc()
}

// ByModelsJSON orders the results by the models_json field.
func ByModelsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelsJSON, opts...).ToFunc()
}

// ByDefaultModel orders the results by the default_model field.
func ByDefaultModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultModel, opts...).ToFunc()
}

// ByTimeout orders the results by the timeout field.
func ByTimeout(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeout, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
