// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttachTokensColumns holds the columns for the "attach_tokens" table.
	AttachTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString, Default: ""},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AttachTokensTable holds the schema information for the "attach_tokens" table.
	AttachTokensTable = &schema.Table{
		Name:       "attach_tokens",
		Columns:    AttachTokensColumns,
		PrimaryKey: []*schema.Column{AttachTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "attachtoken_token",
				Unique:  true,
				Columns: []*schema.Column{AttachTokensColumns[1]},
			},
			{
				Name:    "attachtoken_session_id",
				Unique:  false,
				Columns: []*schema.Column{AttachTokensColumns[2]},
			},
			{
				Name:    "attachtoken_owner",
				Unique:  false,
				Columns: []*schema.Column{AttachTokensColumns[3]},
			},
			{
				Name:    "attachtoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AttachTokensColumns[4]},
			},
		},
	}
	// ToolEventsColumns holds the columns for the "tool_events" table.
	ToolEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload_json", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ToolEventsTable holds the schema information for the "tool_events" table.
	ToolEventsTable = &schema.Table{
		Name:       "tool_events",
		Columns:    ToolEventsColumns,
		PrimaryKey: []*schema.Column{ToolEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "toolevent_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ToolEventsColumns[1], ToolEventsColumns[4]},
			},
			{
				Name:    "toolevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{ToolEventsColumns[2]},
			},
		},
	}
	// ToolSessionsColumns holds the columns for the "tool_sessions" table.
	ToolSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString, Default: ""},
		{Name: "source", Type: field.TypeString, Default: "webui"},
		{Name: "channel", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "conversation_key", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "tool", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "command", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "workdir", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "state", Type: field.TypeString, Default: "running"},
		{Name: "access_mode", Type: field.TypeString, Default: "none"},
		{Name: "access_secret_hash", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "access_once_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "pinned", Type: field.TypeBool, Default: false},
		{Name: "last_active_at", Type: field.TypeTime},
		{Name: "detached_at", Type: field.TypeTime, Nullable: true},
		{Name: "terminated_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "metadata_json", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ToolSessionsTable holds the schema information for the "tool_sessions" table.
	ToolSessionsTable = &schema.Table{
		Name:       "tool_sessions",
		Columns:    ToolSessionsColumns,
		PrimaryKey: []*schema.Column{ToolSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "toolsession_owner_state",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[1], ToolSessionsColumns[9]},
			},
			{
				Name:    "toolsession_owner_access_mode",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[1], ToolSessionsColumns[10]},
			},
			{
				Name:    "toolsession_source_conversation_key",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[2], ToolSessionsColumns[4]},
			},
			{
				Name:    "toolsession_last_active_at",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[14]},
			},
			{
				Name:    "toolsession_created_at",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[19]},
			},
			{
				Name:    "toolsession_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ToolSessionsColumns[20]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttachTokensTable,
		ToolEventsTable,
		ToolSessionsTable,
	}
)

func init() {
}
