// Code generated by ent, DO NOT EDIT.

package accountbinding

import (
	"nekobot/pkg/storage/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContainsFold(FieldID, id))
}

// ChannelAccountID applies equality check predicate on the "channel_account_id" field. It's identical to ChannelAccountIDEQ.
func ChannelAccountID(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldChannelAccountID, v))
}

// AgentRuntimeID applies equality check predicate on the "agent_runtime_id" field. It's identical to AgentRuntimeIDEQ.
func AgentRuntimeID(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldAgentRuntimeID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldEnabled, v))
}

// AllowPublicReply applies equality check predicate on the "allow_public_reply" field. It's identical to AllowPublicReplyEQ.
func AllowPublicReply(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldAllowPublicReply, v))
}

// ReplyLabel applies equality check predicate on the "reply_label" field. It's identical to ReplyLabelEQ.
func ReplyLabel(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldReplyLabel, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldPriority, v))
}

// MetadataJSON applies equality check predicate on the "metadata_json" field. It's identical to MetadataJSONEQ.
func MetadataJSON(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldMetadataJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChannelAccountIDEQ applies the EQ predicate on the "channel_account_id" field.
func ChannelAccountIDEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldChannelAccountID, v))
}

// ChannelAccountIDNEQ applies the NEQ predicate on the "channel_account_id" field.
func ChannelAccountIDNEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldChannelAccountID, v))
}

// ChannelAccountIDIn applies the In predicate on the "channel_account_id" field.
func ChannelAccountIDIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldChannelAccountID, vs...))
}

// ChannelAccountIDNotIn applies the NotIn predicate on the "channel_account_id" field.
func ChannelAccountIDNotIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldChannelAccountID, vs...))
}

// ChannelAccountIDGT applies the GT predicate on the "channel_account_id" field.
func ChannelAccountIDGT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldChannelAccountID, v))
}

// ChannelAccountIDGTE applies the GTE predicate on the "channel_account_id" field.
func ChannelAccountIDGTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldChannelAccountID, v))
}

// ChannelAccountIDLT applies the LT predicate on the "channel_account_id" field.
func ChannelAccountIDLT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldChannelAccountID, v))
}

// ChannelAccountIDLTE applies the LTE predicate on the "channel_account_id" field.
func ChannelAccountIDLTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldChannelAccountID, v))
}

// ChannelAccountIDContains applies the Contains predicate on the "channel_account_id" field.
func ChannelAccountIDContains(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContains(FieldChannelAccountID, v))
}

// ChannelAccountIDHasPrefix applies the HasPrefix predicate on the "channel_account_id" field.
func ChannelAccountIDHasPrefix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasPrefix(FieldChannelAccountID, v))
}

// ChannelAccountIDHasSuffix applies the HasSuffix predicate on the "channel_account_id" field.
func ChannelAccountIDHasSuffix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasSuffix(FieldChannelAccountID, v))
}

// ChannelAccountIDEqualFold applies the EqualFold predicate on the "channel_account_id" field.
func ChannelAccountIDEqualFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEqualFold(FieldChannelAccountID, v))
}

// ChannelAccountIDContainsFold applies the ContainsFold predicate on the "channel_account_id" field.
func ChannelAccountIDContainsFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContainsFold(FieldChannelAccountID, v))
}

// AgentRuntimeIDEQ applies the EQ predicate on the "agent_runtime_id" field.
func AgentRuntimeIDEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDNEQ applies the NEQ predicate on the "agent_runtime_id" field.
func AgentRuntimeIDNEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDIn applies the In predicate on the "agent_runtime_id" field.
func AgentRuntimeIDIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldAgentRuntimeID, vs...))
}

// AgentRuntimeIDNotIn applies the NotIn predicate on the "agent_runtime_id" field.
func AgentRuntimeIDNotIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldAgentRuntimeID, vs...))
}

// AgentRuntimeIDGT applies the GT predicate on the "agent_runtime_id" field.
func AgentRuntimeIDGT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDGTE applies the GTE predicate on the "agent_runtime_id" field.
func AgentRuntimeIDGTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDLT applies the LT predicate on the "agent_runtime_id" field.
func AgentRuntimeIDLT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDLTE applies the LTE predicate on the "agent_runtime_id" field.
func AgentRuntimeIDLTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDContains applies the Contains predicate on the "agent_runtime_id" field.
func AgentRuntimeIDContains(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContains(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDHasPrefix applies the HasPrefix predicate on the "agent_runtime_id" field.
func AgentRuntimeIDHasPrefix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasPrefix(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDHasSuffix applies the HasSuffix predicate on the "agent_runtime_id" field.
func AgentRuntimeIDHasSuffix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasSuffix(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDEqualFold applies the EqualFold predicate on the "agent_runtime_id" field.
func AgentRuntimeIDEqualFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEqualFold(FieldAgentRuntimeID, v))
}

// AgentRuntimeIDContainsFold applies the ContainsFold predicate on the "agent_runtime_id" field.
func AgentRuntimeIDContainsFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContainsFold(FieldAgentRuntimeID, v))
}

// BindingModeEQ applies the EQ predicate on the "binding_mode" field.
func BindingModeEQ(v BindingMode) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldBindingMode, v))
}

// BindingModeNEQ applies the NEQ predicate on the "binding_mode" field.
func BindingModeNEQ(v BindingMode) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldBindingMode, v))
}

// BindingModeIn applies the In predicate on the "binding_mode" field.
func BindingModeIn(vs ...BindingMode) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldBindingMode, vs...))
}

// BindingModeNotIn applies the NotIn predicate on the "binding_mode" field.
func BindingModeNotIn(vs ...BindingMode) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldBindingMode, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldEnabled, v))
}

// AllowPublicReplyEQ applies the EQ predicate on the "allow_public_reply" field.
func AllowPublicReplyEQ(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldAllowPublicReply, v))
}

// AllowPublicReplyNEQ applies the NEQ predicate on the "allow_public_reply" field.
func AllowPublicReplyNEQ(v bool) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldAllowPublicReply, v))
}

// ReplyLabelEQ applies the EQ predicate on the "reply_label" field.
func ReplyLabelEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldReplyLabel, v))
}

// ReplyLabelNEQ applies the NEQ predicate on the "reply_label" field.
func ReplyLabelNEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldReplyLabel, v))
}

// ReplyLabelIn applies the In predicate on the "reply_label" field.
func ReplyLabelIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldReplyLabel, vs...))
}

// ReplyLabelNotIn applies the NotIn predicate on the "reply_label" field.
func ReplyLabelNotIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldReplyLabel, vs...))
}

// ReplyLabelGT applies the GT predicate on the "reply_label" field.
func ReplyLabelGT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldReplyLabel, v))
}

// ReplyLabelGTE applies the GTE predicate on the "reply_label" field.
func ReplyLabelGTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldReplyLabel, v))
}

// ReplyLabelLT applies the LT predicate on the "reply_label" field.
func ReplyLabelLT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldReplyLabel, v))
}

// ReplyLabelLTE applies the LTE predicate on the "reply_label" field.
func ReplyLabelLTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldReplyLabel, v))
}

// ReplyLabelContains applies the Contains predicate on the "reply_label" field.
func ReplyLabelContains(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContains(FieldReplyLabel, v))
}

// ReplyLabelHasPrefix applies the HasPrefix predicate on the "reply_label" field.
func ReplyLabelHasPrefix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasPrefix(FieldReplyLabel, v))
}

// ReplyLabelHasSuffix applies the HasSuffix predicate on the "reply_label" field.
func ReplyLabelHasSuffix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasSuffix(FieldReplyLabel, v))
}

// ReplyLabelEqualFold applies the EqualFold predicate on the "reply_label" field.
func ReplyLabelEqualFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEqualFold(FieldReplyLabel, v))
}

// ReplyLabelContainsFold applies the ContainsFold predicate on the "reply_label" field.
func ReplyLabelContainsFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContainsFold(FieldReplyLabel, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldPriority, v))
}

// MetadataJSONEQ applies the EQ predicate on the "metadata_json" field.
func MetadataJSONEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldMetadataJSON, v))
}

// MetadataJSONNEQ applies the NEQ predicate on the "metadata_json" field.
func MetadataJSONNEQ(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldMetadataJSON, v))
}

// MetadataJSONIn applies the In predicate on the "metadata_json" field.
func MetadataJSONIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldMetadataJSON, vs...))
}

// MetadataJSONNotIn applies the NotIn predicate on the "metadata_json" field.
func MetadataJSONNotIn(vs ...string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldMetadataJSON, vs...))
}

// MetadataJSONGT applies the GT predicate on the "metadata_json" field.
func MetadataJSONGT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldMetadataJSON, v))
}

// MetadataJSONGTE applies the GTE predicate on the "metadata_json" field.
func MetadataJSONGTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldMetadataJSON, v))
}

// MetadataJSONLT applies the LT predicate on the "metadata_json" field.
func MetadataJSONLT(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldMetadataJSON, v))
}

// MetadataJSONLTE applies the LTE predicate on the "metadata_json" field.
func MetadataJSONLTE(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldMetadataJSON, v))
}

// MetadataJSONContains applies the Contains predicate on the "metadata_json" field.
func MetadataJSONContains(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContains(FieldMetadataJSON, v))
}

// MetadataJSONHasPrefix applies the HasPrefix predicate on the "metadata_json" field.
func MetadataJSONHasPrefix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasPrefix(FieldMetadataJSON, v))
}

// MetadataJSONHasSuffix applies the HasSuffix predicate on the "metadata_json" field.
func MetadataJSONHasSuffix(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldHasSuffix(FieldMetadataJSON, v))
}

// MetadataJSONEqualFold applies the EqualFold predicate on the "metadata_json" field.
func MetadataJSONEqualFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEqualFold(FieldMetadataJSON, v))
}

// MetadataJSONContainsFold applies the ContainsFold predicate on the "metadata_json" field.
func MetadataJSONContainsFold(v string) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldContainsFold(FieldMetadataJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountBinding {
	return predicate.AccountBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountBinding) predicate.AccountBinding {
	return predicate.AccountBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountBinding) predicate.AccountBinding {
	return predicate.AccountBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountBinding) predicate.AccountBinding {
	return predicate.AccountBinding(sql.NotPredicates(p))
}
