// Code generated by ent, DO NOT EDIT.

package promptbinding

import (
	"nekobot/pkg/storage/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldContainsFold(FieldID, id))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldTarget, v))
}

// PromptID applies equality check predicate on the "prompt_id" field. It's identical to PromptIDEQ.
func PromptID(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldPromptID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldPriority, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v Scope) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v Scope) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...Scope) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...Scope) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldScope, vs...))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldContainsFold(FieldTarget, v))
}

// PromptIDEQ applies the EQ predicate on the "prompt_id" field.
func PromptIDEQ(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldPromptID, v))
}

// PromptIDNEQ applies the NEQ predicate on the "prompt_id" field.
func PromptIDNEQ(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldPromptID, v))
}

// PromptIDIn applies the In predicate on the "prompt_id" field.
func PromptIDIn(vs ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldPromptID, vs...))
}

// PromptIDNotIn applies the NotIn predicate on the "prompt_id" field.
func PromptIDNotIn(vs ...string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldPromptID, vs...))
}

// PromptIDGT applies the GT predicate on the "prompt_id" field.
func PromptIDGT(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldPromptID, v))
}

// PromptIDGTE applies the GTE predicate on the "prompt_id" field.
func PromptIDGTE(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldPromptID, v))
}

// PromptIDLT applies the LT predicate on the "prompt_id" field.
func PromptIDLT(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldPromptID, v))
}

// PromptIDLTE applies the LTE predicate on the "prompt_id" field.
func PromptIDLTE(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldPromptID, v))
}

// PromptIDContains applies the Contains predicate on the "prompt_id" field.
func PromptIDContains(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldContains(FieldPromptID, v))
}

// PromptIDHasPrefix applies the HasPrefix predicate on the "prompt_id" field.
func PromptIDHasPrefix(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldHasPrefix(FieldPromptID, v))
}

// PromptIDHasSuffix applies the HasSuffix predicate on the "prompt_id" field.
func PromptIDHasSuffix(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldHasSuffix(FieldPromptID, v))
}

// PromptIDEqualFold applies the EqualFold predicate on the "prompt_id" field.
func PromptIDEqualFold(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEqualFold(FieldPromptID, v))
}

// PromptIDContainsFold applies the ContainsFold predicate on the "prompt_id" field.
func PromptIDContainsFold(v string) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldContainsFold(FieldPromptID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldPriority, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromptBinding {
	return predicate.PromptBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptBinding) predicate.PromptBinding {
	return predicate.PromptBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptBinding) predicate.PromptBinding {
	return predicate.PromptBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptBinding) predicate.PromptBinding {
	return predicate.PromptBinding(sql.NotPredicates(p))
}
