// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/agentruntime"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentRuntimeCreate is the builder for creating a AgentRuntime entity.
type AgentRuntimeCreate struct {
	config
	mutation *AgentRuntimeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AgentRuntimeCreate) SetName(v string) *AgentRuntimeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AgentRuntimeCreate) SetDisplayName(v string) *AgentRuntimeCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableDisplayName(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgentRuntimeCreate) SetDescription(v string) *AgentRuntimeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableDescription(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AgentRuntimeCreate) SetEnabled(v bool) *AgentRuntimeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableEnabled(v *bool) *AgentRuntimeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AgentRuntimeCreate) SetProvider(v string) *AgentRuntimeCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableProvider(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AgentRuntimeCreate) SetModel(v string) *AgentRuntimeCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableModel(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetPromptID sets the "prompt_id" field.
func (_c *AgentRuntimeCreate) SetPromptID(v string) *AgentRuntimeCreate {
	_c.mutation.SetPromptID(v)
	return _c
}

// SetNillablePromptID sets the "prompt_id" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillablePromptID(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetPromptID(*v)
	}
	return _c
}

// SetSkillsJSON sets the "skills_json" field.
func (_c *AgentRuntimeCreate) SetSkillsJSON(v string) *AgentRuntimeCreate {
	_c.mutation.SetSkillsJSON(v)
	return _c
}

// SetNillableSkillsJSON sets the "skills_json" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableSkillsJSON(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetSkillsJSON(*v)
	}
	return _c
}

// SetToolsJSON sets the "tools_json" field.
func (_c *AgentRuntimeCreate) SetToolsJSON(v string) *AgentRuntimeCreate {
	_c.mutation.SetToolsJSON(v)
	return _c
}

// SetNillableToolsJSON sets the "tools_json" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableToolsJSON(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetToolsJSON(*v)
	}
	return _c
}

// SetPolicyJSON sets the "policy_json" field.
func (_c *AgentRuntimeCreate) SetPolicyJSON(v string) *AgentRuntimeCreate {
	_c.mutation.SetPolicyJSON(v)
	return _c
}

// SetNillablePolicyJSON sets the "policy_json" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillablePolicyJSON(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetPolicyJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentRuntimeCreate) SetCreatedAt(v time.Time) *AgentRuntimeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableCreatedAt(v *time.Time) *AgentRuntimeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentRuntimeCreate) SetUpdatedAt(v time.Time) *AgentRuntimeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableUpdatedAt(v *time.Time) *AgentRuntimeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentRuntimeCreate) SetID(v string) *AgentRuntimeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentRuntimeCreate) SetNillableID(v *string) *AgentRuntimeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AgentRuntimeMutation object of the builder.
func (_c *AgentRuntimeCreate) Mutation() *AgentRuntimeMutation {
	return _c.mutation
}

// Save creates the AgentRuntime in the database.
func (_c *AgentRuntimeCreate) Save(ctx context.Context) (*AgentRuntime, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentRuntimeCreate) SaveX(ctx context.Context) *AgentRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRuntimeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRuntimeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentRuntimeCreate) defaults() {
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := agentruntime.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := agentruntime.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := agentruntime.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := agentruntime.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := agentruntime.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.PromptID(); !ok {
		v := agentruntime.DefaultPromptID
		_c.mutation.SetPromptID(v)
	}
	if _, ok := _c.mutation.SkillsJSON(); !ok {
		v := agentruntime.DefaultSkillsJSON
		_c.mutation.SetSkillsJSON(v)
	}
	if _, ok := _c.mutation.ToolsJSON(); !ok {
		v := agentruntime.DefaultToolsJSON
		_c.mutation.SetToolsJSON(v)
	}
	if _, ok := _c.mutation.PolicyJSON(); !ok {
		v := agentruntime.DefaultPolicyJSON
		_c.mutation.SetPolicyJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentruntime.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentruntime.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agentruntime.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentRuntimeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentRuntime.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentruntime.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentRuntime.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "AgentRuntime.display_name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "AgentRuntime.description"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AgentRuntime.enabled"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AgentRuntime.provider"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AgentRuntime.model"`)}
	}
	if _, ok := _c.mutation.PromptID(); !ok {
		return &ValidationError{Name: "prompt_id", err: errors.New(`ent: missing required field "AgentRuntime.prompt_id"`)}
	}
	if _, ok := _c.mutation.SkillsJSON(); !ok {
		return &ValidationError{Name: "skills_json", err: errors.New(`ent: missing required field "AgentRuntime.skills_json"`)}
	}
	if _, ok := _c.mutation.ToolsJSON(); !ok {
		return &ValidationError{Name: "tools_json", err: errors.New(`ent: missing required field "AgentRuntime.tools_json"`)}
	}
	if _, ok := _c.mutation.PolicyJSON(); !ok {
		return &ValidationError{Name: "policy_json", err: errors.New(`ent: missing required field "AgentRuntime.policy_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentRuntime.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentRuntime.updated_at"`)}
	}
	return nil
}

func (_c *AgentRuntimeCreate) sqlSave(ctx context.Context) (*AgentRuntime, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentRuntime.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentRuntimeCreate) createSpec() (*AgentRuntime, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentRuntime{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentruntime.Table, sqlgraph.NewFieldSpec(agentruntime.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentruntime.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(agentruntime.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agentruntime.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(agentruntime.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(agentruntime.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(agentruntime.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.PromptID(); ok {
		_spec.SetField(agentruntime.FieldPromptID, field.TypeString, value)
		_node.PromptID = value
	}
	if value, ok := _c.mutation.SkillsJSON(); ok {
		_spec.SetField(agentruntime.FieldSkillsJSON, field.TypeString, value)
		_node.SkillsJSON = value
	}
	if value, ok := _c.mutation.ToolsJSON(); ok {
		_spec.SetField(agentruntime.FieldToolsJSON, field.TypeString, value)
		_node.ToolsJSON = value
	}
	if value, ok := _c.mutation.PolicyJSON(); ok {
		_spec.SetField(agentruntime.FieldPolicyJSON, field.TypeString, value)
		_node.PolicyJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentruntime.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentruntime.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AgentRuntimeCreateBulk is the builder for creating many AgentRuntime entities in bulk.
type AgentRuntimeCreateBulk struct {
	config
	err      error
	builders []*AgentRuntimeCreate
}

// Save creates the AgentRuntime entities in the database.
func (_c *AgentRuntimeCreateBulk) Save(ctx context.Context) ([]*AgentRuntime, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentRuntime, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentRuntimeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentRuntimeCreateBulk) SaveX(ctx context.Context) []*AgentRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRuntimeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRuntimeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
