// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"nekobot/pkg/storage/ent/migrate"

	"nekobot/pkg/storage/ent/attachtoken"
	"nekobot/pkg/storage/ent/configsection"
	"nekobot/pkg/storage/ent/cronjob"
	"nekobot/pkg/storage/ent/provider"
	"nekobot/pkg/storage/ent/toolevent"
	"nekobot/pkg/storage/ent/toolsession"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AttachToken is the client for interacting with the AttachToken builders.
	AttachToken *AttachTokenClient
	// ConfigSection is the client for interacting with the ConfigSection builders.
	ConfigSection *ConfigSectionClient
	// CronJob is the client for interacting with the CronJob builders.
	CronJob *CronJobClient
	// Provider is the client for interacting with the Provider builders.
	Provider *ProviderClient
	// ToolEvent is the client for interacting with the ToolEvent builders.
	ToolEvent *ToolEventClient
	// ToolSession is the client for interacting with the ToolSession builders.
	ToolSession *ToolSessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AttachToken = NewAttachTokenClient(c.config)
	c.ConfigSection = NewConfigSectionClient(c.config)
	c.CronJob = NewCronJobClient(c.config)
	c.Provider = NewProviderClient(c.config)
	c.ToolEvent = NewToolEventClient(c.config)
	c.ToolSession = NewToolSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AttachToken:   NewAttachTokenClient(cfg),
		ConfigSection: NewConfigSectionClient(cfg),
		CronJob:       NewCronJobClient(cfg),
		Provider:      NewProviderClient(cfg),
		ToolEvent:     NewToolEventClient(cfg),
		ToolSession:   NewToolSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AttachToken:   NewAttachTokenClient(cfg),
		ConfigSection: NewConfigSectionClient(cfg),
		CronJob:       NewCronJobClient(cfg),
		Provider:      NewProviderClient(cfg),
		ToolEvent:     NewToolEventClient(cfg),
		ToolSession:   NewToolSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AttachToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AttachToken, c.ConfigSection, c.CronJob, c.Provider, c.ToolEvent,
		c.ToolSession,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AttachToken, c.ConfigSection, c.CronJob, c.Provider, c.ToolEvent,
		c.ToolSession,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AttachTokenMutation:
		return c.AttachToken.mutate(ctx, m)
	case *ConfigSectionMutation:
		return c.ConfigSection.mutate(ctx, m)
	case *CronJobMutation:
		return c.CronJob.mutate(ctx, m)
	case *ProviderMutation:
		return c.Provider.mutate(ctx, m)
	case *ToolEventMutation:
		return c.ToolEvent.mutate(ctx, m)
	case *ToolSessionMutation:
		return c.ToolSession.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AttachTokenClient is a client for the AttachToken schema.
type AttachTokenClient struct {
	config
}

// NewAttachTokenClient returns a client for the AttachToken from the given config.
func NewAttachTokenClient(c config) *AttachTokenClient {
	return &AttachTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attachtoken.Hooks(f(g(h())))`.
func (c *AttachTokenClient) Use(hooks ...Hook) {
	c.hooks.AttachToken = append(c.hooks.AttachToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attachtoken.Intercept(f(g(h())))`.
func (c *AttachTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.AttachToken = append(c.inters.AttachToken, interceptors...)
}

// Create returns a builder for creating a AttachToken entity.
func (c *AttachTokenClient) Create() *AttachTokenCreate {
	mutation := newAttachTokenMutation(c.config, OpCreate)
	return &AttachTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AttachToken entities.
func (c *AttachTokenClient) CreateBulk(builders ...*AttachTokenCreate) *AttachTokenCreateBulk {
	return &AttachTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttachTokenClient) MapCreateBulk(slice any, setFunc func(*AttachTokenCreate, int)) *AttachTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttachTokenCreateBulk{err: fmt.Errorf("calling to AttachTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttachTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttachTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AttachToken.
func (c *AttachTokenClient) Update() *AttachTokenUpdate {
	mutation := newAttachTokenMutation(c.config, OpUpdate)
	return &AttachTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttachTokenClient) UpdateOne(_m *AttachToken) *AttachTokenUpdateOne {
	mutation := newAttachTokenMutation(c.config, OpUpdateOne, withAttachToken(_m))
	return &AttachTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttachTokenClient) UpdateOneID(id string) *AttachTokenUpdateOne {
	mutation := newAttachTokenMutation(c.config, OpUpdateOne, withAttachTokenID(id))
	return &AttachTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AttachToken.
func (c *AttachTokenClient) Delete() *AttachTokenDelete {
	mutation := newAttachTokenMutation(c.config, OpDelete)
	return &AttachTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttachTokenClient) DeleteOne(_m *AttachToken) *AttachTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttachTokenClient) DeleteOneID(id string) *AttachTokenDeleteOne {
	builder := c.Delete().Where(attachtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttachTokenDeleteOne{builder}
}

// Query returns a query builder for AttachToken.
func (c *AttachTokenClient) Query() *AttachTokenQuery {
	return &AttachTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttachToken},
		inters: c.Interceptors(),
	}
}

// Get returns a AttachToken entity by its id.
func (c *AttachTokenClient) Get(ctx context.Context, id string) (*AttachToken, error) {
	return c.Query().Where(attachtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttachTokenClient) GetX(ctx context.Context, id string) *AttachToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AttachTokenClient) Hooks() []Hook {
	return c.hooks.AttachToken
}

// Interceptors returns the client interceptors.
func (c *AttachTokenClient) Interceptors() []Interceptor {
	return c.inters.AttachToken
}

func (c *AttachTokenClient) mutate(ctx context.Context, m *AttachTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttachTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttachTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttachTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttachTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AttachToken mutation op: %q", m.Op())
	}
}

// ConfigSectionClient is a client for the ConfigSection schema.
type ConfigSectionClient struct {
	config
}

// NewConfigSectionClient returns a client for the ConfigSection from the given config.
func NewConfigSectionClient(c config) *ConfigSectionClient {
	return &ConfigSectionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `configsection.Hooks(f(g(h())))`.
func (c *ConfigSectionClient) Use(hooks ...Hook) {
	c.hooks.ConfigSection = append(c.hooks.ConfigSection, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `configsection.Intercept(f(g(h())))`.
func (c *ConfigSectionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConfigSection = append(c.inters.ConfigSection, interceptors...)
}

// Create returns a builder for creating a ConfigSection entity.
func (c *ConfigSectionClient) Create() *ConfigSectionCreate {
	mutation := newConfigSectionMutation(c.config, OpCreate)
	return &ConfigSectionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConfigSection entities.
func (c *ConfigSectionClient) CreateBulk(builders ...*ConfigSectionCreate) *ConfigSectionCreateBulk {
	return &ConfigSectionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConfigSectionClient) MapCreateBulk(slice any, setFunc func(*ConfigSectionCreate, int)) *ConfigSectionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConfigSectionCreateBulk{err: fmt.Errorf("calling to ConfigSectionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConfigSectionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConfigSectionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConfigSection.
func (c *ConfigSectionClient) Update() *ConfigSectionUpdate {
	mutation := newConfigSectionMutation(c.config, OpUpdate)
	return &ConfigSectionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConfigSectionClient) UpdateOne(_m *ConfigSection) *ConfigSectionUpdateOne {
	mutation := newConfigSectionMutation(c.config, OpUpdateOne, withConfigSection(_m))
	return &ConfigSectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConfigSectionClient) UpdateOneID(id int) *ConfigSectionUpdateOne {
	mutation := newConfigSectionMutation(c.config, OpUpdateOne, withConfigSectionID(id))
	return &ConfigSectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConfigSection.
func (c *ConfigSectionClient) Delete() *ConfigSectionDelete {
	mutation := newConfigSectionMutation(c.config, OpDelete)
	return &ConfigSectionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConfigSectionClient) DeleteOne(_m *ConfigSection) *ConfigSectionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConfigSectionClient) DeleteOneID(id int) *ConfigSectionDeleteOne {
	builder := c.Delete().Where(configsection.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConfigSectionDeleteOne{builder}
}

// Query returns a query builder for ConfigSection.
func (c *ConfigSectionClient) Query() *ConfigSectionQuery {
	return &ConfigSectionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConfigSection},
		inters: c.Interceptors(),
	}
}

// Get returns a ConfigSection entity by its id.
func (c *ConfigSectionClient) Get(ctx context.Context, id int) (*ConfigSection, error) {
	return c.Query().Where(configsection.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConfigSectionClient) GetX(ctx context.Context, id int) *ConfigSection {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ConfigSectionClient) Hooks() []Hook {
	return c.hooks.ConfigSection
}

// Interceptors returns the client interceptors.
func (c *ConfigSectionClient) Interceptors() []Interceptor {
	return c.inters.ConfigSection
}

func (c *ConfigSectionClient) mutate(ctx context.Context, m *ConfigSectionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConfigSectionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConfigSectionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConfigSectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConfigSectionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConfigSection mutation op: %q", m.Op())
	}
}

// CronJobClient is a client for the CronJob schema.
type CronJobClient struct {
	config
}

// NewCronJobClient returns a client for the CronJob from the given config.
func NewCronJobClient(c config) *CronJobClient {
	return &CronJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cronjob.Hooks(f(g(h())))`.
func (c *CronJobClient) Use(hooks ...Hook) {
	c.hooks.CronJob = append(c.hooks.CronJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cronjob.Intercept(f(g(h())))`.
func (c *CronJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.CronJob = append(c.inters.CronJob, interceptors...)
}

// Create returns a builder for creating a CronJob entity.
func (c *CronJobClient) Create() *CronJobCreate {
	mutation := newCronJobMutation(c.config, OpCreate)
	return &CronJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CronJob entities.
func (c *CronJobClient) CreateBulk(builders ...*CronJobCreate) *CronJobCreateBulk {
	return &CronJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CronJobClient) MapCreateBulk(slice any, setFunc func(*CronJobCreate, int)) *CronJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CronJobCreateBulk{err: fmt.Errorf("calling to CronJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CronJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CronJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CronJob.
func (c *CronJobClient) Update() *CronJobUpdate {
	mutation := newCronJobMutation(c.config, OpUpdate)
	return &CronJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CronJobClient) UpdateOne(_m *CronJob) *CronJobUpdateOne {
	mutation := newCronJobMutation(c.config, OpUpdateOne, withCronJob(_m))
	return &CronJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CronJobClient) UpdateOneID(id string) *CronJobUpdateOne {
	mutation := newCronJobMutation(c.config, OpUpdateOne, withCronJobID(id))
	return &CronJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CronJob.
func (c *CronJobClient) Delete() *CronJobDelete {
	mutation := newCronJobMutation(c.config, OpDelete)
	return &CronJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CronJobClient) DeleteOne(_m *CronJob) *CronJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CronJobClient) DeleteOneID(id string) *CronJobDeleteOne {
	builder := c.Delete().Where(cronjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CronJobDeleteOne{builder}
}

// Query returns a query builder for CronJob.
func (c *CronJobClient) Query() *CronJobQuery {
	return &CronJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCronJob},
		inters: c.Interceptors(),
	}
}

// Get returns a CronJob entity by its id.
func (c *CronJobClient) Get(ctx context.Context, id string) (*CronJob, error) {
	return c.Query().Where(cronjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CronJobClient) GetX(ctx context.Context, id string) *CronJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CronJobClient) Hooks() []Hook {
	return c.hooks.CronJob
}

// Interceptors returns the client interceptors.
func (c *CronJobClient) Interceptors() []Interceptor {
	return c.inters.CronJob
}

func (c *CronJobClient) mutate(ctx context.Context, m *CronJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CronJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CronJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CronJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CronJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CronJob mutation op: %q", m.Op())
	}
}

// ProviderClient is a client for the Provider schema.
type ProviderClient struct {
	config
}

// NewProviderClient returns a client for the Provider from the given config.
func NewProviderClient(c config) *ProviderClient {
	return &ProviderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `provider.Hooks(f(g(h())))`.
func (c *ProviderClient) Use(hooks ...Hook) {
	c.hooks.Provider = append(c.hooks.Provider, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `provider.Intercept(f(g(h())))`.
func (c *ProviderClient) Intercept(interceptors ...Interceptor) {
	c.inters.Provider = append(c.inters.Provider, interceptors...)
}

// Create returns a builder for creating a Provider entity.
func (c *ProviderClient) Create() *ProviderCreate {
	mutation := newProviderMutation(c.config, OpCreate)
	return &ProviderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Provider entities.
func (c *ProviderClient) CreateBulk(builders ...*ProviderCreate) *ProviderCreateBulk {
	return &ProviderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProviderClient) MapCreateBulk(slice any, setFunc func(*ProviderCreate, int)) *ProviderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProviderCreateBulk{err: fmt.Errorf("calling to ProviderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProviderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProviderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Provider.
func (c *ProviderClient) Update() *ProviderUpdate {
	mutation := newProviderMutation(c.config, OpUpdate)
	return &ProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProviderClient) UpdateOne(_m *Provider) *ProviderUpdateOne {
	mutation := newProviderMutation(c.config, OpUpdateOne, withProvider(_m))
	return &ProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProviderClient) UpdateOneID(id string) *ProviderUpdateOne {
	mutation := newProviderMutation(c.config, OpUpdateOne, withProviderID(id))
	return &ProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Provider.
func (c *ProviderClient) Delete() *ProviderDelete {
	mutation := newProviderMutation(c.config, OpDelete)
	return &ProviderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProviderClient) DeleteOne(_m *Provider) *ProviderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProviderClient) DeleteOneID(id string) *ProviderDeleteOne {
	builder := c.Delete().Where(provider.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProviderDeleteOne{builder}
}

// Query returns a query builder for Provider.
func (c *ProviderClient) Query() *ProviderQuery {
	return &ProviderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProvider},
		inters: c.Interceptors(),
	}
}

// Get returns a Provider entity by its id.
func (c *ProviderClient) Get(ctx context.Context, id string) (*Provider, error) {
	return c.Query().Where(provider.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProviderClient) GetX(ctx context.Context, id string) *Provider {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProviderClient) Hooks() []Hook {
	return c.hooks.Provider
}

// Interceptors returns the client interceptors.
func (c *ProviderClient) Interceptors() []Interceptor {
	return c.inters.Provider
}

func (c *ProviderClient) mutate(ctx context.Context, m *ProviderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProviderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProviderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Provider mutation op: %q", m.Op())
	}
}

// ToolEventClient is a client for the ToolEvent schema.
type ToolEventClient struct {
	config
}

// NewToolEventClient returns a client for the ToolEvent from the given config.
func NewToolEventClient(c config) *ToolEventClient {
	return &ToolEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `toolevent.Hooks(f(g(h())))`.
func (c *ToolEventClient) Use(hooks ...Hook) {
	c.hooks.ToolEvent = append(c.hooks.ToolEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `toolevent.Intercept(f(g(h())))`.
func (c *ToolEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.ToolEvent = append(c.inters.ToolEvent, interceptors...)
}

// Create returns a builder for creating a ToolEvent entity.
func (c *ToolEventClient) Create() *ToolEventCreate {
	mutation := newToolEventMutation(c.config, OpCreate)
	return &ToolEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ToolEvent entities.
func (c *ToolEventClient) CreateBulk(builders ...*ToolEventCreate) *ToolEventCreateBulk {
	return &ToolEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ToolEventClient) MapCreateBulk(slice any, setFunc func(*ToolEventCreate, int)) *ToolEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ToolEventCreateBulk{err: fmt.Errorf("calling to ToolEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ToolEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ToolEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ToolEvent.
func (c *ToolEventClient) Update() *ToolEventUpdate {
	mutation := newToolEventMutation(c.config, OpUpdate)
	return &ToolEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ToolEventClient) UpdateOne(_m *ToolEvent) *ToolEventUpdateOne {
	mutation := newToolEventMutation(c.config, OpUpdateOne, withToolEvent(_m))
	return &ToolEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ToolEventClient) UpdateOneID(id string) *ToolEventUpdateOne {
	mutation := newToolEventMutation(c.config, OpUpdateOne, withToolEventID(id))
	return &ToolEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ToolEvent.
func (c *ToolEventClient) Delete() *ToolEventDelete {
	mutation := newToolEventMutation(c.config, OpDelete)
	return &ToolEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ToolEventClient) DeleteOne(_m *ToolEvent) *ToolEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ToolEventClient) DeleteOneID(id string) *ToolEventDeleteOne {
	builder := c.Delete().Where(toolevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ToolEventDeleteOne{builder}
}

// Query returns a query builder for ToolEvent.
func (c *ToolEventClient) Query() *ToolEventQuery {
	return &ToolEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeToolEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a ToolEvent entity by its id.
func (c *ToolEventClient) Get(ctx context.Context, id string) (*ToolEvent, error) {
	return c.Query().Where(toolevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ToolEventClient) GetX(ctx context.Context, id string) *ToolEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ToolEventClient) Hooks() []Hook {
	return c.hooks.ToolEvent
}

// Interceptors returns the client interceptors.
func (c *ToolEventClient) Interceptors() []Interceptor {
	return c.inters.ToolEvent
}

func (c *ToolEventClient) mutate(ctx context.Context, m *ToolEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ToolEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ToolEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ToolEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ToolEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ToolEvent mutation op: %q", m.Op())
	}
}

// ToolSessionClient is a client for the ToolSession schema.
type ToolSessionClient struct {
	config
}

// NewToolSessionClient returns a client for the ToolSession from the given config.
func NewToolSessionClient(c config) *ToolSessionClient {
	return &ToolSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `toolsession.Hooks(f(g(h())))`.
func (c *ToolSessionClient) Use(hooks ...Hook) {
	c.hooks.ToolSession = append(c.hooks.ToolSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `toolsession.Intercept(f(g(h())))`.
func (c *ToolSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ToolSession = append(c.inters.ToolSession, interceptors...)
}

// Create returns a builder for creating a ToolSession entity.
func (c *ToolSessionClient) Create() *ToolSessionCreate {
	mutation := newToolSessionMutation(c.config, OpCreate)
	return &ToolSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ToolSession entities.
func (c *ToolSessionClient) CreateBulk(builders ...*ToolSessionCreate) *ToolSessionCreateBulk {
	return &ToolSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ToolSessionClient) MapCreateBulk(slice any, setFunc func(*ToolSessionCreate, int)) *ToolSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ToolSessionCreateBulk{err: fmt.Errorf("calling to ToolSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ToolSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ToolSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ToolSession.
func (c *ToolSessionClient) Update() *ToolSessionUpdate {
	mutation := newToolSessionMutation(c.config, OpUpdate)
	return &ToolSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ToolSessionClient) UpdateOne(_m *ToolSession) *ToolSessionUpdateOne {
	mutation := newToolSessionMutation(c.config, OpUpdateOne, withToolSession(_m))
	return &ToolSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ToolSessionClient) UpdateOneID(id string) *ToolSessionUpdateOne {
	mutation := newToolSessionMutation(c.config, OpUpdateOne, withToolSessionID(id))
	return &ToolSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ToolSession.
func (c *ToolSessionClient) Delete() *ToolSessionDelete {
	mutation := newToolSessionMutation(c.config, OpDelete)
	return &ToolSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ToolSessionClient) DeleteOne(_m *ToolSession) *ToolSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ToolSessionClient) DeleteOneID(id string) *ToolSessionDeleteOne {
	builder := c.Delete().Where(toolsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ToolSessionDeleteOne{builder}
}

// Query returns a query builder for ToolSession.
func (c *ToolSessionClient) Query() *ToolSessionQuery {
	return &ToolSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeToolSession},
		inters: c.Interceptors(),
	}
}

// Get returns a ToolSession entity by its id.
func (c *ToolSessionClient) Get(ctx context.Context, id string) (*ToolSession, error) {
	return c.Query().Where(toolsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ToolSessionClient) GetX(ctx context.Context, id string) *ToolSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ToolSessionClient) Hooks() []Hook {
	return c.hooks.ToolSession
}

// Interceptors returns the client interceptors.
func (c *ToolSessionClient) Interceptors() []Interceptor {
	return c.inters.ToolSession
}

func (c *ToolSessionClient) mutate(ctx context.Context, m *ToolSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ToolSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ToolSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ToolSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ToolSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ToolSession mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AttachToken, ConfigSection, CronJob, Provider, ToolEvent, ToolSession []ent.Hook
	}
	inters struct {
		AttachToken, ConfigSection, CronJob, Provider, ToolEvent,
		ToolSession []ent.Interceptor
	}
)
