// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/cronjob"
	"nekobot/pkg/storage/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CronJobUpdate is the builder for updating CronJob entities.
type CronJobUpdate struct {
	config
	hooks    []Hook
	mutation *CronJobMutation
}

// Where appends a list predicates to the CronJobUpdate builder.
func (_u *CronJobUpdate) Where(ps ...predicate.CronJob) *CronJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CronJobUpdate) SetName(v string) *CronJobUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableName(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScheduleKind sets the "schedule_kind" field.
func (_u *CronJobUpdate) SetScheduleKind(v string) *CronJobUpdate {
	_u.mutation.SetScheduleKind(v)
	return _u
}

// SetNillableScheduleKind sets the "schedule_kind" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableScheduleKind(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetScheduleKind(*v)
	}
	return _u
}

// SetSchedule sets the "schedule" field.
func (_u *CronJobUpdate) SetSchedule(v string) *CronJobUpdate {
	_u.mutation.SetSchedule(v)
	return _u
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableSchedule(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetSchedule(*v)
	}
	return _u
}

// SetAtTime sets the "at_time" field.
func (_u *CronJobUpdate) SetAtTime(v time.Time) *CronJobUpdate {
	_u.mutation.SetAtTime(v)
	return _u
}

// SetNillableAtTime sets the "at_time" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableAtTime(v *time.Time) *CronJobUpdate {
	if v != nil {
		_u.SetAtTime(*v)
	}
	return _u
}

// ClearAtTime clears the value of the "at_time" field.
func (_u *CronJobUpdate) ClearAtTime() *CronJobUpdate {
	_u.mutation.ClearAtTime()
	return _u
}

// SetEveryDuration sets the "every_duration" field.
func (_u *CronJobUpdate) SetEveryDuration(v string) *CronJobUpdate {
	_u.mutation.SetEveryDuration(v)
	return _u
}

// SetNillableEveryDuration sets the "every_duration" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableEveryDuration(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetEveryDuration(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *CronJobUpdate) SetPrompt(v string) *CronJobUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillablePrompt(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CronJobUpdate) SetEnabled(v bool) *CronJobUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableEnabled(v *bool) *CronJobUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDeleteAfterRun sets the "delete_after_run" field.
func (_u *CronJobUpdate) SetDeleteAfterRun(v bool) *CronJobUpdate {
	_u.mutation.SetDeleteAfterRun(v)
	return _u
}

// SetNillableDeleteAfterRun sets the "delete_after_run" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableDeleteAfterRun(v *bool) *CronJobUpdate {
	if v != nil {
		_u.SetDeleteAfterRun(*v)
	}
	return _u
}

// SetLastRun sets the "last_run" field.
func (_u *CronJobUpdate) SetLastRun(v time.Time) *CronJobUpdate {
	_u.mutation.SetLastRun(v)
	return _u
}

// SetNillableLastRun sets the "last_run" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableLastRun(v *time.Time) *CronJobUpdate {
	if v != nil {
		_u.SetLastRun(*v)
	}
	return _u
}

// ClearLastRun clears the value of the "last_run" field.
func (_u *CronJobUpdate) ClearLastRun() *CronJobUpdate {
	_u.mutation.ClearLastRun()
	return _u
}

// SetNextRun sets the "next_run" field.
func (_u *CronJobUpdate) SetNextRun(v time.Time) *CronJobUpdate {
	_u.mutation.SetNextRun(v)
	return _u
}

// SetNillableNextRun sets the "next_run" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableNextRun(v *time.Time) *CronJobUpdate {
	if v != nil {
		_u.SetNextRun(*v)
	}
	return _u
}

// ClearNextRun clears the value of the "next_run" field.
func (_u *CronJobUpdate) ClearNextRun() *CronJobUpdate {
	_u.mutation.ClearNextRun()
	return _u
}

// SetRunCount sets the "run_count" field.
func (_u *CronJobUpdate) SetRunCount(v int) *CronJobUpdate {
	_u.mutation.ResetRunCount()
	_u.mutation.SetRunCount(v)
	return _u
}

// SetNillableRunCount sets the "run_count" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableRunCount(v *int) *CronJobUpdate {
	if v != nil {
		_u.SetRunCount(*v)
	}
	return _u
}

// AddRunCount adds value to the "run_count" field.
func (_u *CronJobUpdate) AddRunCount(v int) *CronJobUpdate {
	_u.mutation.AddRunCount(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CronJobUpdate) SetLastError(v string) *CronJobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableLastError(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastSuccess sets the "last_success" field.
func (_u *CronJobUpdate) SetLastSuccess(v bool) *CronJobUpdate {
	_u.mutation.SetLastSuccess(v)
	return _u
}

// SetNillableLastSuccess sets the "last_success" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableLastSuccess(v *bool) *CronJobUpdate {
	if v != nil {
		_u.SetLastSuccess(*v)
	}
	return _u
}

// Mutation returns the CronJobMutation object of the builder.
func (_u *CronJobUpdate) Mutation() *CronJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CronJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CronJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CronJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CronJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CronJobUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := cronjob.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "CronJob.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *CronJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleKind(); ok {
		_spec.SetField(cronjob.FieldScheduleKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Schedule(); ok {
		_spec.SetField(cronjob.FieldSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.AtTime(); ok {
		_spec.SetField(cronjob.FieldAtTime, field.TypeTime, value)
	}
	if _u.mutation.AtTimeCleared() {
		_spec.ClearField(cronjob.FieldAtTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EveryDuration(); ok {
		_spec.SetField(cronjob.FieldEveryDuration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(cronjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeleteAfterRun(); ok {
		_spec.SetField(cronjob.FieldDeleteAfterRun, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRun(); ok {
		_spec.SetField(cronjob.FieldLastRun, field.TypeTime, value)
	}
	if _u.mutation.LastRunCleared() {
		_spec.ClearField(cronjob.FieldLastRun, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRun(); ok {
		_spec.SetField(cronjob.FieldNextRun, field.TypeTime, value)
	}
	if _u.mutation.NextRunCleared() {
		_spec.ClearField(cronjob.FieldNextRun, field.TypeTime)
	}
	if value, ok := _u.mutation.RunCount(); ok {
		_spec.SetField(cronjob.FieldRunCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRunCount(); ok {
		_spec.AddField(cronjob.FieldRunCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cronjob.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSuccess(); ok {
		_spec.SetField(cronjob.FieldLastSuccess, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CronJobUpdateOne is the builder for updating a single CronJob entity.
type CronJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CronJobMutation
}

// SetName sets the "name" field.
func (_u *CronJobUpdateOne) SetName(v string) *CronJobUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableName(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScheduleKind sets the "schedule_kind" field.
func (_u *CronJobUpdateOne) SetScheduleKind(v string) *CronJobUpdateOne {
	_u.mutation.SetScheduleKind(v)
	return _u
}

// SetNillableScheduleKind sets the "schedule_kind" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableScheduleKind(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetScheduleKind(*v)
	}
	return _u
}

// SetSchedule sets the "schedule" field.
func (_u *CronJobUpdateOne) SetSchedule(v string) *CronJobUpdateOne {
	_u.mutation.SetSchedule(v)
	return _u
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableSchedule(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetSchedule(*v)
	}
	return _u
}

// SetAtTime sets the "at_time" field.
func (_u *CronJobUpdateOne) SetAtTime(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetAtTime(v)
	return _u
}

// SetNillableAtTime sets the "at_time" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableAtTime(v *time.Time) *CronJobUpdateOne {
	if v != nil {
		_u.SetAtTime(*v)
	}
	return _u
}

// ClearAtTime clears the value of the "at_time" field.
func (_u *CronJobUpdateOne) ClearAtTime() *CronJobUpdateOne {
	_u.mutation.ClearAtTime()
	return _u
}

// SetEveryDuration sets the "every_duration" field.
func (_u *CronJobUpdateOne) SetEveryDuration(v string) *CronJobUpdateOne {
	_u.mutation.SetEveryDuration(v)
	return _u
}

// SetNillableEveryDuration sets the "every_duration" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableEveryDuration(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetEveryDuration(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *CronJobUpdateOne) SetPrompt(v string) *CronJobUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillablePrompt(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CronJobUpdateOne) SetEnabled(v bool) *CronJobUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableEnabled(v *bool) *CronJobUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDeleteAfterRun sets the "delete_after_run" field.
func (_u *CronJobUpdateOne) SetDeleteAfterRun(v bool) *CronJobUpdateOne {
	_u.mutation.SetDeleteAfterRun(v)
	return _u
}

// SetNillableDeleteAfterRun sets the "delete_after_run" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableDeleteAfterRun(v *bool) *CronJobUpdateOne {
	if v != nil {
		_u.SetDeleteAfterRun(*v)
	}
	return _u
}

// SetLastRun sets the "last_run" field.
func (_u *CronJobUpdateOne) SetLastRun(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetLastRun(v)
	return _u
}

// SetNillableLastRun sets the "last_run" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableLastRun(v *time.Time) *CronJobUpdateOne {
	if v != nil {
		_u.SetLastRun(*v)
	}
	return _u
}

// ClearLastRun clears the value of the "last_run" field.
func (_u *CronJobUpdateOne) ClearLastRun() *CronJobUpdateOne {
	_u.mutation.ClearLastRun()
	return _u
}

// SetNextRun sets the "next_run" field.
func (_u *CronJobUpdateOne) SetNextRun(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetNextRun(v)
	return _u
}

// SetNillableNextRun sets the "next_run" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableNextRun(v *time.Time) *CronJobUpdateOne {
	if v != nil {
		_u.SetNextRun(*v)
	}
	return _u
}

// ClearNextRun clears the value of the "next_run" field.
func (_u *CronJobUpdateOne) ClearNextRun() *CronJobUpdateOne {
	_u.mutation.ClearNextRun()
	return _u
}

// SetRunCount sets the "run_count" field.
func (_u *CronJobUpdateOne) SetRunCount(v int) *CronJobUpdateOne {
	_u.mutation.ResetRunCount()
	_u.mutation.SetRunCount(v)
	return _u
}

// SetNillableRunCount sets the "run_count" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableRunCount(v *int) *CronJobUpdateOne {
	if v != nil {
		_u.SetRunCount(*v)
	}
	return _u
}

// AddRunCount adds value to the "run_count" field.
func (_u *CronJobUpdateOne) AddRunCount(v int) *CronJobUpdateOne {
	_u.mutation.AddRunCount(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CronJobUpdateOne) SetLastError(v string) *CronJobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableLastError(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastSuccess sets the "last_success" field.
func (_u *CronJobUpdateOne) SetLastSuccess(v bool) *CronJobUpdateOne {
	_u.mutation.SetLastSuccess(v)
	return _u
}

// SetNillableLastSuccess sets the "last_success" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableLastSuccess(v *bool) *CronJobUpdateOne {
	if v != nil {
		_u.SetLastSuccess(*v)
	}
	return _u
}

// Mutation returns the CronJobMutation object of the builder.
func (_u *CronJobUpdateOne) Mutation() *CronJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the CronJobUpdate builder.
func (_u *CronJobUpdateOne) Where(ps ...predicate.CronJob) *CronJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CronJobUpdateOne) Select(field string, fields ...string) *CronJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CronJob entity.
func (_u *CronJobUpdateOne) Save(ctx context.Context) (*CronJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CronJobUpdateOne) SaveX(ctx context.Context) *CronJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CronJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CronJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CronJobUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := cronjob.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "CronJob.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *CronJobUpdateOne) sqlSave(ctx context.Context) (_node *CronJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CronJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cronjob.FieldID)
		for _, f := range fields {
			if !cronjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cronjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleKind(); ok {
		_spec.SetField(cronjob.FieldScheduleKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Schedule(); ok {
		_spec.SetField(cronjob.FieldSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.AtTime(); ok {
		_spec.SetField(cronjob.FieldAtTime, field.TypeTime, value)
	}
	if _u.mutation.AtTimeCleared() {
		_spec.ClearField(cronjob.FieldAtTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EveryDuration(); ok {
		_spec.SetField(cronjob.FieldEveryDuration, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(cronjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeleteAfterRun(); ok {
		_spec.SetField(cronjob.FieldDeleteAfterRun, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRun(); ok {
		_spec.SetField(cronjob.FieldLastRun, field.TypeTime, value)
	}
	if _u.mutation.LastRunCleared() {
		_spec.ClearField(cronjob.FieldLastRun, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRun(); ok {
		_spec.SetField(cronjob.FieldNextRun, field.TypeTime, value)
	}
	if _u.mutation.NextRunCleared() {
		_spec.ClearField(cronjob.FieldNextRun, field.TypeTime)
	}
	if value, ok := _u.mutation.RunCount(); ok {
		_spec.SetField(cronjob.FieldRunCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRunCount(); ok {
		_spec.AddField(cronjob.FieldRunCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cronjob.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSuccess(); ok {
		_spec.SetField(cronjob.FieldLastSuccess, field.TypeBool, value)
	}
	_node = &CronJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
