// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/idempotencyrecord"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IdempotencyRecordCreate is the builder for creating a IdempotencyRecord entity.
type IdempotencyRecordCreate struct {
	config
	mutation *IdempotencyRecordMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *IdempotencyRecordCreate) SetTenantID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableTenantID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCallerKind sets the "caller_kind" field.
func (_c *IdempotencyRecordCreate) SetCallerKind(v string) *IdempotencyRecordCreate {
	_c.mutation.SetCallerKind(v)
	return _c
}

// SetNillableCallerKind sets the "caller_kind" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableCallerKind(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetCallerKind(*v)
	}
	return _c
}

// SetCallerID sets the "caller_id" field.
func (_c *IdempotencyRecordCreate) SetCallerID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetCallerID(v)
	return _c
}

// SetNillableCallerID sets the "caller_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableCallerID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetCallerID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *IdempotencyRecordCreate) SetMethod(v string) *IdempotencyRecordCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableMethod(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *IdempotencyRecordCreate) SetRequestID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableRequestID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *IdempotencyRecordCreate) SetRequestHash(v string) *IdempotencyRecordCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableRequestHash(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetRequestHash(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IdempotencyRecordCreate) SetStatus(v string) *IdempotencyRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableStatus(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResponseType sets the "response_type" field.
func (_c *IdempotencyRecordCreate) SetResponseType(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResponseType(v)
	return _c
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResponseType(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResponseType(*v)
	}
	return _c
}

// SetResponseJSON sets the "response_json" field.
func (_c *IdempotencyRecordCreate) SetResponseJSON(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResponseJSON(v)
	return _c
}

// SetNillableResponseJSON sets the "response_json" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResponseJSON(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResponseJSON(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *IdempotencyRecordCreate) SetErrorCode(v string) *IdempotencyRecordCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableErrorCode(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *IdempotencyRecordCreate) SetErrorMessage(v string) *IdempotencyRecordCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableErrorMessage(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetResourceKind sets the "resource_kind" field.
func (_c *IdempotencyRecordCreate) SetResourceKind(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResourceKind(v)
	return _c
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResourceKind(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResourceKind(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *IdempotencyRecordCreate) SetResourceID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResourceID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *IdempotencyRecordCreate) SetEventID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableEventID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetEventID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdempotencyRecordCreate) SetCreatedAt(v time.Time) *IdempotencyRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableCreatedAt(v *time.Time) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IdempotencyRecordCreate) SetUpdatedAt(v time.Time) *IdempotencyRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableUpdatedAt(v *time.Time) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *IdempotencyRecordCreate) SetExpiresAt(v time.Time) *IdempotencyRecordCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableExpiresAt(v *time.Time) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IdempotencyRecordCreate) SetID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IdempotencyRecordMutation object of the builder.
func (_c *IdempotencyRecordCreate) Mutation() *IdempotencyRecordMutation {
	return _c.mutation
}

// Save creates the IdempotencyRecord in the database.
func (_c *IdempotencyRecordCreate) Save(ctx context.Context) (*IdempotencyRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdempotencyRecordCreate) SaveX(ctx context.Context) *IdempotencyRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdempotencyRecordCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := idempotencyrecord.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CallerKind(); !ok {
		v := idempotencyrecord.DefaultCallerKind
		_c.mutation.SetCallerKind(v)
	}
	if _, ok := _c.mutation.CallerID(); !ok {
		v := idempotencyrecord.DefaultCallerID
		_c.mutation.SetCallerID(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := idempotencyrecord.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := idempotencyrecord.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		v := idempotencyrecord.DefaultRequestHash
		_c.mutation.SetRequestHash(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := idempotencyrecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		v := idempotencyrecord.DefaultResponseType
		_c.mutation.SetResponseType(v)
	}
	if _, ok := _c.mutation.ResponseJSON(); !ok {
		v := idempotencyrecord.DefaultResponseJSON
		_c.mutation.SetResponseJSON(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := idempotencyrecord.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := idempotencyrecord.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.ResourceKind(); !ok {
		v := idempotencyrecord.DefaultResourceKind
		_c.mutation.SetResourceKind(v)
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		v := idempotencyrecord.DefaultResourceID
		_c.mutation.SetResourceID(v)
	}
	if _, ok := _c.mutation.EventID(); !ok {
		v := idempotencyrecord.DefaultEventID
		_c.mutation.SetEventID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := idempotencyrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := idempotencyrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := idempotencyrecord.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := idempotencyrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdempotencyRecordCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "IdempotencyRecord.tenant_id"`)}
	}
	if _, ok := _c.mutation.CallerKind(); !ok {
		return &ValidationError{Name: "caller_kind", err: errors.New(`ent: missing required field "IdempotencyRecord.caller_kind"`)}
	}
	if _, ok := _c.mutation.CallerID(); !ok {
		return &ValidationError{Name: "caller_id", err: errors.New(`ent: missing required field "IdempotencyRecord.caller_id"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "IdempotencyRecord.method"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "IdempotencyRecord.request_id"`)}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "IdempotencyRecord.request_hash"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IdempotencyRecord.status"`)}
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		return &ValidationError{Name: "response_type", err: errors.New(`ent: missing required field "IdempotencyRecord.response_type"`)}
	}
	if _, ok := _c.mutation.ResponseJSON(); !ok {
		return &ValidationError{Name: "response_json", err: errors.New(`ent: missing required field "IdempotencyRecord.response_json"`)}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "IdempotencyRecord.error_code"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "IdempotencyRecord.error_message"`)}
	}
	if _, ok := _c.mutation.ResourceKind(); !ok {
		return &ValidationError{Name: "resource_kind", err: errors.New(`ent: missing required field "IdempotencyRecord.resource_kind"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "IdempotencyRecord.resource_id"`)}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "IdempotencyRecord.event_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IdempotencyRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IdempotencyRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "IdempotencyRecord.expires_at"`)}
	}
	return nil
}

func (_c *IdempotencyRecordCreate) sqlSave(ctx context.Context) (*IdempotencyRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IdempotencyRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdempotencyRecordCreate) createSpec() (*IdempotencyRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &IdempotencyRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(idempotencyrecord.Table, sqlgraph.NewFieldSpec(idempotencyrecord.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(idempotencyrecord.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CallerKind(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerKind, field.TypeString, value)
		_node.CallerKind = value
	}
	if value, ok := _c.mutation.CallerID(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerID, field.TypeString, value)
		_node.CallerID = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(idempotencyrecord.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(idempotencyrecord.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ResponseType(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseType, field.TypeString, value)
		_node.ResponseType = value
	}
	if value, ok := _c.mutation.ResponseJSON(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseJSON, field.TypeString, value)
		_node.ResponseJSON = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.ResourceKind(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceKind, field.TypeString, value)
		_node.ResourceKind = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(idempotencyrecord.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(idempotencyrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(idempotencyrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencyrecord.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// IdempotencyRecordCreateBulk is the builder for creating many IdempotencyRecord entities in bulk.
type IdempotencyRecordCreateBulk struct {
	config
	err      error
	builders []*IdempotencyRecordCreate
}

// Save creates the IdempotencyRecord entities in the database.
func (_c *IdempotencyRecordCreateBulk) Save(ctx context.Context) ([]*IdempotencyRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdempotencyRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdempotencyRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdempotencyRecordCreateBulk) SaveX(ctx context.Context) []*IdempotencyRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
