// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/idempotencyrecord"
	"nekobot/pkg/storage/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IdempotencyRecordUpdate is the builder for updating IdempotencyRecord entities.
type IdempotencyRecordUpdate struct {
	config
	hooks    []Hook
	mutation *IdempotencyRecordMutation
}

// Where appends a list predicates to the IdempotencyRecordUpdate builder.
func (_u *IdempotencyRecordUpdate) Where(ps ...predicate.IdempotencyRecord) *IdempotencyRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *IdempotencyRecordUpdate) SetTenantID(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableTenantID(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCallerKind sets the "caller_kind" field.
func (_u *IdempotencyRecordUpdate) SetCallerKind(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetCallerKind(v)
	return _u
}

// SetNillableCallerKind sets the "caller_kind" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableCallerKind(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetCallerKind(*v)
	}
	return _u
}

// SetCallerID sets the "caller_id" field.
func (_u *IdempotencyRecordUpdate) SetCallerID(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetCallerID(v)
	return _u
}

// SetNillableCallerID sets the "caller_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableCallerID(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetCallerID(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *IdempotencyRecordUpdate) SetMethod(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableMethod(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *IdempotencyRecordUpdate) SetRequestID(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableRequestID(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *IdempotencyRecordUpdate) SetRequestHash(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableRequestHash(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IdempotencyRecordUpdate) SetStatus(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableStatus(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResponseType sets the "response_type" field.
func (_u *IdempotencyRecordUpdate) SetResponseType(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetResponseType(v)
	return _u
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableResponseType(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetResponseType(*v)
	}
	return _u
}

// SetResponseJSON sets the "response_json" field.
func (_u *IdempotencyRecordUpdate) SetResponseJSON(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetResponseJSON(v)
	return _u
}

// SetNillableResponseJSON sets the "response_json" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableResponseJSON(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetResponseJSON(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *IdempotencyRecordUpdate) SetErrorCode(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableErrorCode(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *IdempotencyRecordUpdate) SetErrorMessage(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableErrorMessage(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetResourceKind sets the "resource_kind" field.
func (_u *IdempotencyRecordUpdate) SetResourceKind(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetResourceKind(v)
	return _u
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableResourceKind(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetResourceKind(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *IdempotencyRecordUpdate) SetResourceID(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableResourceID(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *IdempotencyRecordUpdate) SetEventID(v string) *IdempotencyRecordUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableEventID(v *string) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdempotencyRecordUpdate) SetUpdatedAt(v time.Time) *IdempotencyRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IdempotencyRecordUpdate) SetExpiresAt(v time.Time) *IdempotencyRecordUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IdempotencyRecordUpdate) SetNillableExpiresAt(v *time.Time) *IdempotencyRecordUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the IdempotencyRecordMutation object of the builder.
func (_u *IdempotencyRecordUpdate) Mutation() *IdempotencyRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdempotencyRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdempotencyRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdempotencyRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdempotencyRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdempotencyRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idempotencyrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *IdempotencyRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(idempotencyrecord.Table, idempotencyrecord.Columns, sqlgraph.NewFieldSpec(idempotencyrecord.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(idempotencyrecord.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallerKind(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallerID(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(idempotencyrecord.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(idempotencyrecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseType(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseJSON(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceKind(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(idempotencyrecord.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idempotencyrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencyrecord.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencyrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdempotencyRecordUpdateOne is the builder for updating a single IdempotencyRecord entity.
type IdempotencyRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdempotencyRecordMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *IdempotencyRecordUpdateOne) SetTenantID(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableTenantID(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCallerKind sets the "caller_kind" field.
func (_u *IdempotencyRecordUpdateOne) SetCallerKind(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetCallerKind(v)
	return _u
}

// SetNillableCallerKind sets the "caller_kind" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableCallerKind(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetCallerKind(*v)
	}
	return _u
}

// SetCallerID sets the "caller_id" field.
func (_u *IdempotencyRecordUpdateOne) SetCallerID(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetCallerID(v)
	return _u
}

// SetNillableCallerID sets the "caller_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableCallerID(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetCallerID(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *IdempotencyRecordUpdateOne) SetMethod(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableMethod(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *IdempotencyRecordUpdateOne) SetRequestID(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableRequestID(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *IdempotencyRecordUpdateOne) SetRequestHash(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableRequestHash(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IdempotencyRecordUpdateOne) SetStatus(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableStatus(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResponseType sets the "response_type" field.
func (_u *IdempotencyRecordUpdateOne) SetResponseType(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetResponseType(v)
	return _u
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableResponseType(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetResponseType(*v)
	}
	return _u
}

// SetResponseJSON sets the "response_json" field.
func (_u *IdempotencyRecordUpdateOne) SetResponseJSON(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetResponseJSON(v)
	return _u
}

// SetNillableResponseJSON sets the "response_json" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableResponseJSON(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetResponseJSON(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *IdempotencyRecordUpdateOne) SetErrorCode(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableErrorCode(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *IdempotencyRecordUpdateOne) SetErrorMessage(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableErrorMessage(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetResourceKind sets the "resource_kind" field.
func (_u *IdempotencyRecordUpdateOne) SetResourceKind(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetResourceKind(v)
	return _u
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableResourceKind(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetResourceKind(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *IdempotencyRecordUpdateOne) SetResourceID(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableResourceID(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *IdempotencyRecordUpdateOne) SetEventID(v string) *IdempotencyRecordUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableEventID(v *string) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdempotencyRecordUpdateOne) SetUpdatedAt(v time.Time) *IdempotencyRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IdempotencyRecordUpdateOne) SetExpiresAt(v time.Time) *IdempotencyRecordUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IdempotencyRecordUpdateOne) SetNillableExpiresAt(v *time.Time) *IdempotencyRecordUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the IdempotencyRecordMutation object of the builder.
func (_u *IdempotencyRecordUpdateOne) Mutation() *IdempotencyRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdempotencyRecordUpdate builder.
func (_u *IdempotencyRecordUpdateOne) Where(ps ...predicate.IdempotencyRecord) *IdempotencyRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdempotencyRecordUpdateOne) Select(field string, fields ...string) *IdempotencyRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdempotencyRecord entity.
func (_u *IdempotencyRecordUpdateOne) Save(ctx context.Context) (*IdempotencyRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdempotencyRecordUpdateOne) SaveX(ctx context.Context) *IdempotencyRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdempotencyRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdempotencyRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdempotencyRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idempotencyrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *IdempotencyRecordUpdateOne) sqlSave(ctx context.Context) (_node *IdempotencyRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(idempotencyrecord.Table, idempotencyrecord.Columns, sqlgraph.NewFieldSpec(idempotencyrecord.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdempotencyRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencyrecord.FieldID)
		for _, f := range fields {
			if !idempotencyrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idempotencyrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(idempotencyrecord.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallerKind(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallerID(); ok {
		_spec.SetField(idempotencyrecord.FieldCallerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(idempotencyrecord.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(idempotencyrecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseType(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseJSON(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(idempotencyrecord.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceKind(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(idempotencyrecord.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idempotencyrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencyrecord.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &IdempotencyRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencyrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
