// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nekobot/pkg/storage/ent/modelroute"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ModelRoute is the model entity for the ModelRoute schema.
type ModelRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// ProviderName holds the value of the "provider_name" field.
	ProviderName string `json:"provider_name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// WeightOverride holds the value of the "weight_override" field.
	WeightOverride int `json:"weight_override,omitempty"`
	// AliasesJSON holds the value of the "aliases_json" field.
	AliasesJSON string `json:"aliases_json,omitempty"`
	// RegexRulesJSON holds the value of the "regex_rules_json" field.
	RegexRulesJSON string `json:"regex_rules_json,omitempty"`
	// MetadataJSON holds the value of the "metadata_json" field.
	MetadataJSON string `json:"metadata_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelroute.FieldEnabled, modelroute.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case modelroute.FieldWeightOverride:
			values[i] = new(sql.NullInt64)
		case modelroute.FieldID, modelroute.FieldModelID, modelroute.FieldProviderName, modelroute.FieldAliasesJSON, modelroute.FieldRegexRulesJSON, modelroute.FieldMetadataJSON:
			values[i] = new(sql.NullString)
		case modelroute.FieldCreatedAt, modelroute.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelRoute fields.
func (_m *ModelRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelroute.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case modelroute.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelroute.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				_m.ProviderName = value.String
			}
		case modelroute.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case modelroute.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case modelroute.FieldWeightOverride:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight_override", values[i])
			} else if value.Valid {
				_m.WeightOverride = int(value.Int64)
			}
		case modelroute.FieldAliasesJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aliases_json", values[i])
			} else if value.Valid {
				_m.AliasesJSON = value.String
			}
		case modelroute.FieldRegexRulesJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field regex_rules_json", values[i])
			} else if value.Valid {
				_m.RegexRulesJSON = value.String
			}
		case modelroute.FieldMetadataJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_json", values[i])
			} else if value.Valid {
				_m.MetadataJSON = value.String
			}
		case modelroute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelroute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelRoute.
// This includes values selected through modifiers, order, etc.
func (_m *ModelRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelRoute.
// Note that you need to call ModelRoute.Unwrap() before calling this method if this ModelRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelRoute) Update() *ModelRouteUpdateOne {
	return NewModelRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelRoute) Unwrap() *ModelRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelRoute) String() string {
	var builder strings.Builder
	builder.WriteString("ModelRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("provider_name=")
	builder.WriteString(_m.ProviderName)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("weight_override=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeightOverride))
	builder.WriteString(", ")
	builder.WriteString("aliases_json=")
	builder.WriteString(_m.AliasesJSON)
	builder.WriteString(", ")
	builder.WriteString("regex_rules_json=")
	builder.WriteString(_m.RegexRulesJSON)
	builder.WriteString(", ")
	builder.WriteString("metadata_json=")
	builder.WriteString(_m.MetadataJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelRoutes is a parsable slice of ModelRoute.
type ModelRoutes []*ModelRoute
