// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nekobot/pkg/storage/ent/modelcatalog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ModelCatalog is the model entity for the ModelCatalog schema.
type ModelCatalog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Developer holds the value of the "developer" field.
	Developer string `json:"developer,omitempty"`
	// Family holds the value of the "family" field.
	Family string `json:"family,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// CapabilitiesJSON holds the value of the "capabilities_json" field.
	CapabilitiesJSON string `json:"capabilities_json,omitempty"`
	// CatalogSource holds the value of the "catalog_source" field.
	CatalogSource string `json:"catalog_source,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalog.FieldEnabled:
			values[i] = new(sql.NullBool)
		case modelcatalog.FieldID, modelcatalog.FieldModelID, modelcatalog.FieldDisplayName, modelcatalog.FieldDeveloper, modelcatalog.FieldFamily, modelcatalog.FieldType, modelcatalog.FieldCapabilitiesJSON, modelcatalog.FieldCatalogSource:
			values[i] = new(sql.NullString)
		case modelcatalog.FieldCreatedAt, modelcatalog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalog fields.
func (_m *ModelCatalog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case modelcatalog.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelcatalog.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case modelcatalog.FieldDeveloper:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field developer", values[i])
			} else if value.Valid {
				_m.Developer = value.String
			}
		case modelcatalog.FieldFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family", values[i])
			} else if value.Valid {
				_m.Family = value.String
			}
		case modelcatalog.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case modelcatalog.FieldCapabilitiesJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities_json", values[i])
			} else if value.Valid {
				_m.CapabilitiesJSON = value.String
			}
		case modelcatalog.FieldCatalogSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field catalog_source", values[i])
			} else if value.Valid {
				_m.CatalogSource = value.String
			}
		case modelcatalog.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case modelcatalog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalog.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelCatalog.
// Note that you need to call ModelCatalog.Unwrap() before calling this method if this ModelCatalog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalog) Update() *ModelCatalogUpdateOne {
	return NewModelCatalogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalog) Unwrap() *ModelCatalog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalog) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("developer=")
	builder.WriteString(_m.Developer)
	builder.WriteString(", ")
	builder.WriteString("family=")
	builder.WriteString(_m.Family)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("capabilities_json=")
	builder.WriteString(_m.CapabilitiesJSON)
	builder.WriteString(", ")
	builder.WriteString("catalog_source=")
	builder.WriteString(_m.CatalogSource)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogs is a parsable slice of ModelCatalog.
type ModelCatalogs []*ModelCatalog
