// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/modelroute"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModelRouteCreate is the builder for creating a ModelRoute entity.
type ModelRouteCreate struct {
	config
	mutation *ModelRouteMutation
	hooks    []Hook
}

// SetModelID sets the "model_id" field.
func (_c *ModelRouteCreate) SetModelID(v string) *ModelRouteCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetProviderName sets the "provider_name" field.
func (_c *ModelRouteCreate) SetProviderName(v string) *ModelRouteCreate {
	_c.mutation.SetProviderName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ModelRouteCreate) SetEnabled(v bool) *ModelRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableEnabled(v *bool) *ModelRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ModelRouteCreate) SetIsDefault(v bool) *ModelRouteCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableIsDefault(v *bool) *ModelRouteCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetWeightOverride sets the "weight_override" field.
func (_c *ModelRouteCreate) SetWeightOverride(v int) *ModelRouteCreate {
	_c.mutation.SetWeightOverride(v)
	return _c
}

// SetNillableWeightOverride sets the "weight_override" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableWeightOverride(v *int) *ModelRouteCreate {
	if v != nil {
		_c.SetWeightOverride(*v)
	}
	return _c
}

// SetAliasesJSON sets the "aliases_json" field.
func (_c *ModelRouteCreate) SetAliasesJSON(v string) *ModelRouteCreate {
	_c.mutation.SetAliasesJSON(v)
	return _c
}

// SetNillableAliasesJSON sets the "aliases_json" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableAliasesJSON(v *string) *ModelRouteCreate {
	if v != nil {
		_c.SetAliasesJSON(*v)
	}
	return _c
}

// SetRegexRulesJSON sets the "regex_rules_json" field.
func (_c *ModelRouteCreate) SetRegexRulesJSON(v string) *ModelRouteCreate {
	_c.mutation.SetRegexRulesJSON(v)
	return _c
}

// SetNillableRegexRulesJSON sets the "regex_rules_json" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableRegexRulesJSON(v *string) *ModelRouteCreate {
	if v != nil {
		_c.SetRegexRulesJSON(*v)
	}
	return _c
}

// SetMetadataJSON sets the "metadata_json" field.
func (_c *ModelRouteCreate) SetMetadataJSON(v string) *ModelRouteCreate {
	_c.mutation.SetMetadataJSON(v)
	return _c
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableMetadataJSON(v *string) *ModelRouteCreate {
	if v != nil {
		_c.SetMetadataJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelRouteCreate) SetCreatedAt(v time.Time) *ModelRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableCreatedAt(v *time.Time) *ModelRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelRouteCreate) SetUpdatedAt(v time.Time) *ModelRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableUpdatedAt(v *time.Time) *ModelRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelRouteCreate) SetID(v string) *ModelRouteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableID(v *string) *ModelRouteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ModelRouteMutation object of the builder.
func (_c *ModelRouteCreate) Mutation() *ModelRouteMutation {
	return _c.mutation
}

// Save creates the ModelRoute in the database.
func (_c *ModelRouteCreate) Save(ctx context.Context) (*ModelRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelRouteCreate) SaveX(ctx context.Context) *ModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelRouteCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := modelroute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := modelroute.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.WeightOverride(); !ok {
		v := modelroute.DefaultWeightOverride
		_c.mutation.SetWeightOverride(v)
	}
	if _, ok := _c.mutation.AliasesJSON(); !ok {
		v := modelroute.DefaultAliasesJSON
		_c.mutation.SetAliasesJSON(v)
	}
	if _, ok := _c.mutation.RegexRulesJSON(); !ok {
		v := modelroute.DefaultRegexRulesJSON
		_c.mutation.SetRegexRulesJSON(v)
	}
	if _, ok := _c.mutation.MetadataJSON(); !ok {
		v := modelroute.DefaultMetadataJSON
		_c.mutation.SetMetadataJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modelroute.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelRouteCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ModelRoute.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := modelroute.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderName(); !ok {
		return &ValidationError{Name: "provider_name", err: errors.New(`ent: missing required field "ModelRoute.provider_name"`)}
	}
	if v, ok := _c.mutation.ProviderName(); ok {
		if err := modelroute.ProviderNameValidator(v); err != nil {
			return &ValidationError{Name: "provider_name", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.provider_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ModelRoute.enabled"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ModelRoute.is_default"`)}
	}
	if _, ok := _c.mutation.WeightOverride(); !ok {
		return &ValidationError{Name: "weight_override", err: errors.New(`ent: missing required field "ModelRoute.weight_override"`)}
	}
	if _, ok := _c.mutation.AliasesJSON(); !ok {
		return &ValidationError{Name: "aliases_json", err: errors.New(`ent: missing required field "ModelRoute.aliases_json"`)}
	}
	if _, ok := _c.mutation.RegexRulesJSON(); !ok {
		return &ValidationError{Name: "regex_rules_json", err: errors.New(`ent: missing required field "ModelRoute.regex_rules_json"`)}
	}
	if _, ok := _c.mutation.MetadataJSON(); !ok {
		return &ValidationError{Name: "metadata_json", err: errors.New(`ent: missing required field "ModelRoute.metadata_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelRoute.updated_at"`)}
	}
	return nil
}

func (_c *ModelRouteCreate) sqlSave(ctx context.Context) (*ModelRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ModelRoute.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelRouteCreate) createSpec() (*ModelRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelroute.Table, sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(modelroute.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.ProviderName(); ok {
		_spec.SetField(modelroute.FieldProviderName, field.TypeString, value)
		_node.ProviderName = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(modelroute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(modelroute.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.WeightOverride(); ok {
		_spec.SetField(modelroute.FieldWeightOverride, field.TypeInt, value)
		_node.WeightOverride = value
	}
	if value, ok := _c.mutation.AliasesJSON(); ok {
		_spec.SetField(modelroute.FieldAliasesJSON, field.TypeString, value)
		_node.AliasesJSON = value
	}
	if value, ok := _c.mutation.RegexRulesJSON(); ok {
		_spec.SetField(modelroute.FieldRegexRulesJSON, field.TypeString, value)
		_node.RegexRulesJSON = value
	}
	if value, ok := _c.mutation.MetadataJSON(); ok {
		_spec.SetField(modelroute.FieldMetadataJSON, field.TypeString, value)
		_node.MetadataJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ModelRouteCreateBulk is the builder for creating many ModelRoute entities in bulk.
type ModelRouteCreateBulk struct {
	config
	err      error
	builders []*ModelRouteCreate
}

// Save creates the ModelRoute entities in the database.
func (_c *ModelRouteCreateBulk) Save(ctx context.Context) ([]*ModelRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelRouteCreateBulk) SaveX(ctx context.Context) []*ModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
