// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/notificationbinding"
	"nekobot/pkg/storage/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationBindingUpdate is the builder for updating NotificationBinding entities.
type NotificationBindingUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationBindingMutation
}

// Where appends a list predicates to the NotificationBindingUpdate builder.
func (_u *NotificationBindingUpdate) Where(ps ...predicate.NotificationBinding) *NotificationBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotificationBindingUpdate) SetScope(v string) *NotificationBindingUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableScope(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *NotificationBindingUpdate) SetTarget(v string) *NotificationBindingUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableTarget(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *NotificationBindingUpdate) SetRouteID(v string) *NotificationBindingUpdate {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableRouteID(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetEventTypesJSON sets the "event_types_json" field.
func (_u *NotificationBindingUpdate) SetEventTypesJSON(v string) *NotificationBindingUpdate {
	_u.mutation.SetEventTypesJSON(v)
	return _u
}

// SetNillableEventTypesJSON sets the "event_types_json" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableEventTypesJSON(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetEventTypesJSON(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationBindingUpdate) SetEnabled(v bool) *NotificationBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableEnabled(v *bool) *NotificationBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *NotificationBindingUpdate) SetTenantID(v string) *NotificationBindingUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableTenantID(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *NotificationBindingUpdate) SetOwnerUserID(v string) *NotificationBindingUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableOwnerUserID(v *string) *NotificationBindingUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *NotificationBindingUpdate) SetVisibility(v notificationbinding.Visibility) *NotificationBindingUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *NotificationBindingUpdate) SetNillableVisibility(v *notificationbinding.Visibility) *NotificationBindingUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationBindingUpdate) SetUpdatedAt(v time.Time) *NotificationBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NotificationBindingMutation object of the builder.
func (_u *NotificationBindingUpdate) Mutation() *NotificationBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationBindingUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := notificationbinding.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteID(); ok {
		if err := notificationbinding.RouteIDValidator(v); err != nil {
			return &ValidationError{Name: "route_id", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.route_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := notificationbinding.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationbinding.Table, notificationbinding.Columns, sqlgraph.NewFieldSpec(notificationbinding.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notificationbinding.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationbinding.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(notificationbinding.FieldRouteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypesJSON(); ok {
		_spec.SetField(notificationbinding.FieldEventTypesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(notificationbinding.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(notificationbinding.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(notificationbinding.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationBindingUpdateOne is the builder for updating a single NotificationBinding entity.
type NotificationBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationBindingMutation
}

// SetScope sets the "scope" field.
func (_u *NotificationBindingUpdateOne) SetScope(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableScope(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *NotificationBindingUpdateOne) SetTarget(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableTarget(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *NotificationBindingUpdateOne) SetRouteID(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableRouteID(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetEventTypesJSON sets the "event_types_json" field.
func (_u *NotificationBindingUpdateOne) SetEventTypesJSON(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetEventTypesJSON(v)
	return _u
}

// SetNillableEventTypesJSON sets the "event_types_json" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableEventTypesJSON(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetEventTypesJSON(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationBindingUpdateOne) SetEnabled(v bool) *NotificationBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableEnabled(v *bool) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *NotificationBindingUpdateOne) SetTenantID(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableTenantID(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *NotificationBindingUpdateOne) SetOwnerUserID(v string) *NotificationBindingUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableOwnerUserID(v *string) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *NotificationBindingUpdateOne) SetVisibility(v notificationbinding.Visibility) *NotificationBindingUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *NotificationBindingUpdateOne) SetNillableVisibility(v *notificationbinding.Visibility) *NotificationBindingUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationBindingUpdateOne) SetUpdatedAt(v time.Time) *NotificationBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NotificationBindingMutation object of the builder.
func (_u *NotificationBindingUpdateOne) Mutation() *NotificationBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationBindingUpdate builder.
func (_u *NotificationBindingUpdateOne) Where(ps ...predicate.NotificationBinding) *NotificationBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationBindingUpdateOne) Select(field string, fields ...string) *NotificationBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationBinding entity.
func (_u *NotificationBindingUpdateOne) Save(ctx context.Context) (*NotificationBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationBindingUpdateOne) SaveX(ctx context.Context) *NotificationBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := notificationbinding.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteID(); ok {
		if err := notificationbinding.RouteIDValidator(v); err != nil {
			return &ValidationError{Name: "route_id", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.route_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := notificationbinding.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "NotificationBinding.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationBindingUpdateOne) sqlSave(ctx context.Context) (_node *NotificationBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationbinding.Table, notificationbinding.Columns, sqlgraph.NewFieldSpec(notificationbinding.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationbinding.FieldID)
		for _, f := range fields {
			if !notificationbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notificationbinding.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationbinding.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteID(); ok {
		_spec.SetField(notificationbinding.FieldRouteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypesJSON(); ok {
		_spec.SetField(notificationbinding.FieldEventTypesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(notificationbinding.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(notificationbinding.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(notificationbinding.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NotificationBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
