// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/prompt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PromptCreate is the builder for creating a Prompt entity.
type PromptCreate struct {
	config
	mutation *PromptMutation
	hooks    []Hook
}

// SetPromptKey sets the "prompt_key" field.
func (_c *PromptCreate) SetPromptKey(v string) *PromptCreate {
	_c.mutation.SetPromptKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PromptCreate) SetName(v string) *PromptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromptCreate) SetDescription(v string) *PromptCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromptCreate) SetNillableDescription(v *string) *PromptCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *PromptCreate) SetMode(v prompt.Mode) *PromptCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *PromptCreate) SetNillableMode(v *prompt.Mode) *PromptCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetTemplate sets the "template" field.
func (_c *PromptCreate) SetTemplate(v string) *PromptCreate {
	_c.mutation.SetTemplate(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromptCreate) SetEnabled(v bool) *PromptCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromptCreate) SetNillableEnabled(v *bool) *PromptCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTagsJSON sets the "tags_json" field.
func (_c *PromptCreate) SetTagsJSON(v string) *PromptCreate {
	_c.mutation.SetTagsJSON(v)
	return _c
}

// SetNillableTagsJSON sets the "tags_json" field if the given value is not nil.
func (_c *PromptCreate) SetNillableTagsJSON(v *string) *PromptCreate {
	if v != nil {
		_c.SetTagsJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptCreate) SetCreatedAt(v time.Time) *PromptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptCreate) SetNillableCreatedAt(v *time.Time) *PromptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptCreate) SetUpdatedAt(v time.Time) *PromptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptCreate) SetNillableUpdatedAt(v *time.Time) *PromptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromptCreate) SetID(v string) *PromptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromptCreate) SetNillableID(v *string) *PromptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PromptMutation object of the builder.
func (_c *PromptCreate) Mutation() *PromptMutation {
	return _c.mutation
}

// Save creates the Prompt in the database.
func (_c *PromptCreate) Save(ctx context.Context) (*Prompt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptCreate) SaveX(ctx context.Context) *Prompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := prompt.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := prompt.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := prompt.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.TagsJSON(); !ok {
		v := prompt.DefaultTagsJSON
		_c.mutation.SetTagsJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prompt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prompt.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := prompt.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptCreate) check() error {
	if _, ok := _c.mutation.PromptKey(); !ok {
		return &ValidationError{Name: "prompt_key", err: errors.New(`ent: missing required field "Prompt.prompt_key"`)}
	}
	if v, ok := _c.mutation.PromptKey(); ok {
		if err := prompt.PromptKeyValidator(v); err != nil {
			return &ValidationError{Name: "prompt_key", err: fmt.Errorf(`ent: validator failed for field "Prompt.prompt_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Prompt.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := prompt.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Prompt.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Prompt.description"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Prompt.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := prompt.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Prompt.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Template(); !ok {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required field "Prompt.template"`)}
	}
	if v, ok := _c.mutation.Template(); ok {
		if err := prompt.TemplateValidator(v); err != nil {
			return &ValidationError{Name: "template", err: fmt.Errorf(`ent: validator failed for field "Prompt.template": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Prompt.enabled"`)}
	}
	if _, ok := _c.mutation.TagsJSON(); !ok {
		return &ValidationError{Name: "tags_json", err: errors.New(`ent: missing required field "Prompt.tags_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Prompt.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Prompt.updated_at"`)}
	}
	return nil
}

func (_c *PromptCreate) sqlSave(ctx context.Context) (*Prompt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Prompt.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptCreate) createSpec() (*Prompt, *sqlgraph.CreateSpec) {
	var (
		_node = &Prompt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prompt.Table, sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PromptKey(); ok {
		_spec.SetField(prompt.FieldPromptKey, field.TypeString, value)
		_node.PromptKey = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(prompt.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(prompt.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(prompt.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Template(); ok {
		_spec.SetField(prompt.FieldTemplate, field.TypeString, value)
		_node.Template = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(prompt.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.TagsJSON(); ok {
		_spec.SetField(prompt.FieldTagsJSON, field.TypeString, value)
		_node.TagsJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prompt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prompt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PromptCreateBulk is the builder for creating many Prompt entities in bulk.
type PromptCreateBulk struct {
	config
	err      error
	builders []*PromptCreate
}

// Save creates the Prompt entities in the database.
func (_c *PromptCreateBulk) Save(ctx context.Context) ([]*Prompt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Prompt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptCreateBulk) SaveX(ctx context.Context) []*Prompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
