// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/predicate"
	"nekobot/pkg/storage/ent/promptbinding"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PromptBindingUpdate is the builder for updating PromptBinding entities.
type PromptBindingUpdate struct {
	config
	hooks    []Hook
	mutation *PromptBindingMutation
}

// Where appends a list predicates to the PromptBindingUpdate builder.
func (_u *PromptBindingUpdate) Where(ps ...predicate.PromptBinding) *PromptBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *PromptBindingUpdate) SetScope(v promptbinding.Scope) *PromptBindingUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *PromptBindingUpdate) SetNillableScope(v *promptbinding.Scope) *PromptBindingUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *PromptBindingUpdate) SetTarget(v string) *PromptBindingUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *PromptBindingUpdate) SetNillableTarget(v *string) *PromptBindingUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetPromptID sets the "prompt_id" field.
func (_u *PromptBindingUpdate) SetPromptID(v string) *PromptBindingUpdate {
	_u.mutation.SetPromptID(v)
	return _u
}

// SetNillablePromptID sets the "prompt_id" field if the given value is not nil.
func (_u *PromptBindingUpdate) SetNillablePromptID(v *string) *PromptBindingUpdate {
	if v != nil {
		_u.SetPromptID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromptBindingUpdate) SetEnabled(v bool) *PromptBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromptBindingUpdate) SetNillableEnabled(v *bool) *PromptBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PromptBindingUpdate) SetPriority(v int) *PromptBindingUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PromptBindingUpdate) SetNillablePriority(v *int) *PromptBindingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PromptBindingUpdate) AddPriority(v int) *PromptBindingUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptBindingUpdate) SetUpdatedAt(v time.Time) *PromptBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromptBindingMutation object of the builder.
func (_u *PromptBindingUpdate) Mutation() *PromptBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptBindingUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := promptbinding.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "PromptBinding.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptID(); ok {
		if err := promptbinding.PromptIDValidator(v); err != nil {
			return &ValidationError{Name: "prompt_id", err: fmt.Errorf(`ent: validator failed for field "PromptBinding.prompt_id": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptbinding.Table, promptbinding.Columns, sqlgraph.NewFieldSpec(promptbinding.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(promptbinding.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(promptbinding.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptID(); ok {
		_spec.SetField(promptbinding.FieldPromptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promptbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(promptbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(promptbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptBindingUpdateOne is the builder for updating a single PromptBinding entity.
type PromptBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptBindingMutation
}

// SetScope sets the "scope" field.
func (_u *PromptBindingUpdateOne) SetScope(v promptbinding.Scope) *PromptBindingUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *PromptBindingUpdateOne) SetNillableScope(v *promptbinding.Scope) *PromptBindingUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *PromptBindingUpdateOne) SetTarget(v string) *PromptBindingUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *PromptBindingUpdateOne) SetNillableTarget(v *string) *PromptBindingUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetPromptID sets the "prompt_id" field.
func (_u *PromptBindingUpdateOne) SetPromptID(v string) *PromptBindingUpdateOne {
	_u.mutation.SetPromptID(v)
	return _u
}

// SetNillablePromptID sets the "prompt_id" field if the given value is not nil.
func (_u *PromptBindingUpdateOne) SetNillablePromptID(v *string) *PromptBindingUpdateOne {
	if v != nil {
		_u.SetPromptID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromptBindingUpdateOne) SetEnabled(v bool) *PromptBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromptBindingUpdateOne) SetNillableEnabled(v *bool) *PromptBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PromptBindingUpdateOne) SetPriority(v int) *PromptBindingUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PromptBindingUpdateOne) SetNillablePriority(v *int) *PromptBindingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PromptBindingUpdateOne) AddPriority(v int) *PromptBindingUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptBindingUpdateOne) SetUpdatedAt(v time.Time) *PromptBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromptBindingMutation object of the builder.
func (_u *PromptBindingUpdateOne) Mutation() *PromptBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromptBindingUpdate builder.
func (_u *PromptBindingUpdateOne) Where(ps ...predicate.PromptBinding) *PromptBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptBindingUpdateOne) Select(field string, fields ...string) *PromptBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptBinding entity.
func (_u *PromptBindingUpdateOne) Save(ctx context.Context) (*PromptBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptBindingUpdateOne) SaveX(ctx context.Context) *PromptBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := promptbinding.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "PromptBinding.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptID(); ok {
		if err := promptbinding.PromptIDValidator(v); err != nil {
			return &ValidationError{Name: "prompt_id", err: fmt.Errorf(`ent: validator failed for field "PromptBinding.prompt_id": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptBindingUpdateOne) sqlSave(ctx context.Context) (_node *PromptBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptbinding.Table, promptbinding.Columns, sqlgraph.NewFieldSpec(promptbinding.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promptbinding.FieldID)
		for _, f := range fields {
			if !promptbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promptbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(promptbinding.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(promptbinding.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptID(); ok {
		_spec.SetField(promptbinding.FieldPromptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promptbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(promptbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(promptbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PromptBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
