// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/predicate"
	"nekobot/pkg/storage/ent/provider"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderUpdate) SetName(v string) *ProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableName(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderKind sets the "provider_kind" field.
func (_u *ProviderUpdate) SetProviderKind(v string) *ProviderUpdate {
	_u.mutation.SetProviderKind(v)
	return _u
}

// SetNillableProviderKind sets the "provider_kind" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProviderKind(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetProviderKind(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *ProviderUpdate) SetAPIKey(v string) *ProviderUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableAPIKey(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPIBase sets the "api_base" field.
func (_u *ProviderUpdate) SetAPIBase(v string) *ProviderUpdate {
	_u.mutation.SetAPIBase(v)
	return _u
}

// SetNillableAPIBase sets the "api_base" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableAPIBase(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetAPIBase(*v)
	}
	return _u
}

// SetProxy sets the "proxy" field.
func (_u *ProviderUpdate) SetProxy(v string) *ProviderUpdate {
	_u.mutation.SetProxy(v)
	return _u
}

// SetNillableProxy sets the "proxy" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProxy(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetProxy(*v)
	}
	return _u
}

// SetDefaultWeight sets the "default_weight" field.
func (_u *ProviderUpdate) SetDefaultWeight(v int) *ProviderUpdate {
	_u.mutation.ResetDefaultWeight()
	_u.mutation.SetDefaultWeight(v)
	return _u
}

// SetNillableDefaultWeight sets the "default_weight" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableDefaultWeight(v *int) *ProviderUpdate {
	if v != nil {
		_u.SetDefaultWeight(*v)
	}
	return _u
}

// AddDefaultWeight adds value to the "default_weight" field.
func (_u *ProviderUpdate) AddDefaultWeight(v int) *ProviderUpdate {
	_u.mutation.AddDefaultWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProviderUpdate) SetEnabled(v bool) *ProviderUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableEnabled(v *bool) *ProviderUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDefaultTestModel sets the "default_test_model" field.
func (_u *ProviderUpdate) SetDefaultTestModel(v string) *ProviderUpdate {
	_u.mutation.SetDefaultTestModel(v)
	return _u
}

// SetNillableDefaultTestModel sets the "default_test_model" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableDefaultTestModel(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetDefaultTestModel(*v)
	}
	return _u
}

// SetAPIFormat sets the "api_format" field.
func (_u *ProviderUpdate) SetAPIFormat(v string) *ProviderUpdate {
	_u.mutation.SetAPIFormat(v)
	return _u
}

// SetNillableAPIFormat sets the "api_format" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableAPIFormat(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetAPIFormat(*v)
	}
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *ProviderUpdate) SetTimeout(v int) *ProviderUpdate {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableTimeout(v *int) *ProviderUpdate {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *ProviderUpdate) AddTimeout(v int) *ProviderUpdate {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdate) SetUpdatedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdate) Mutation() *ProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderKind(); ok {
		if err := provider.ProviderKindValidator(v); err != nil {
			return &ValidationError{Name: "provider_kind", err: fmt.Errorf(`ent: validator failed for field "Provider.provider_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderKind(); ok {
		_spec.SetField(provider.FieldProviderKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(provider.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBase(); ok {
		_spec.SetField(provider.FieldAPIBase, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proxy(); ok {
		_spec.SetField(provider.FieldProxy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultWeight(); ok {
		_spec.SetField(provider.FieldDefaultWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultWeight(); ok {
		_spec.AddField(provider.FieldDefaultWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(provider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultTestModel(); ok {
		_spec.SetField(provider.FieldDefaultTestModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIFormat(); ok {
		_spec.SetField(provider.FieldAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(provider.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(provider.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMutation
}

// SetName sets the "name" field.
func (_u *ProviderUpdateOne) SetName(v string) *ProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableName(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderKind sets the "provider_kind" field.
func (_u *ProviderUpdateOne) SetProviderKind(v string) *ProviderUpdateOne {
	_u.mutation.SetProviderKind(v)
	return _u
}

// SetNillableProviderKind sets the "provider_kind" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProviderKind(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetProviderKind(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *ProviderUpdateOne) SetAPIKey(v string) *ProviderUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableAPIKey(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPIBase sets the "api_base" field.
func (_u *ProviderUpdateOne) SetAPIBase(v string) *ProviderUpdateOne {
	_u.mutation.SetAPIBase(v)
	return _u
}

// SetNillableAPIBase sets the "api_base" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableAPIBase(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetAPIBase(*v)
	}
	return _u
}

// SetProxy sets the "proxy" field.
func (_u *ProviderUpdateOne) SetProxy(v string) *ProviderUpdateOne {
	_u.mutation.SetProxy(v)
	return _u
}

// SetNillableProxy sets the "proxy" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProxy(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetProxy(*v)
	}
	return _u
}

// SetDefaultWeight sets the "default_weight" field.
func (_u *ProviderUpdateOne) SetDefaultWeight(v int) *ProviderUpdateOne {
	_u.mutation.ResetDefaultWeight()
	_u.mutation.SetDefaultWeight(v)
	return _u
}

// SetNillableDefaultWeight sets the "default_weight" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableDefaultWeight(v *int) *ProviderUpdateOne {
	if v != nil {
		_u.SetDefaultWeight(*v)
	}
	return _u
}

// AddDefaultWeight adds value to the "default_weight" field.
func (_u *ProviderUpdateOne) AddDefaultWeight(v int) *ProviderUpdateOne {
	_u.mutation.AddDefaultWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProviderUpdateOne) SetEnabled(v bool) *ProviderUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableEnabled(v *bool) *ProviderUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDefaultTestModel sets the "default_test_model" field.
func (_u *ProviderUpdateOne) SetDefaultTestModel(v string) *ProviderUpdateOne {
	_u.mutation.SetDefaultTestModel(v)
	return _u
}

// SetNillableDefaultTestModel sets the "default_test_model" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableDefaultTestModel(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetDefaultTestModel(*v)
	}
	return _u
}

// SetAPIFormat sets the "api_format" field.
func (_u *ProviderUpdateOne) SetAPIFormat(v string) *ProviderUpdateOne {
	_u.mutation.SetAPIFormat(v)
	return _u
}

// SetNillableAPIFormat sets the "api_format" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableAPIFormat(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetAPIFormat(*v)
	}
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *ProviderUpdateOne) SetTimeout(v int) *ProviderUpdateOne {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableTimeout(v *int) *ProviderUpdateOne {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *ProviderUpdateOne) AddTimeout(v int) *ProviderUpdateOne {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdateOne) SetUpdatedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdateOne) Mutation() *ProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Provider entity.
func (_u *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderKind(); ok {
		if err := provider.ProviderKindValidator(v); err != nil {
			return &ValidationError{Name: "provider_kind", err: fmt.Errorf(`ent: validator failed for field "Provider.provider_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderKind(); ok {
		_spec.SetField(provider.FieldProviderKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(provider.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBase(); ok {
		_spec.SetField(provider.FieldAPIBase, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proxy(); ok {
		_spec.SetField(provider.FieldProxy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultWeight(); ok {
		_spec.SetField(provider.FieldDefaultWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultWeight(); ok {
		_spec.AddField(provider.FieldDefaultWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(provider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultTestModel(); ok {
		_spec.SetField(provider.FieldDefaultTestModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIFormat(); ok {
		_spec.SetField(provider.FieldAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(provider.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(provider.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Provider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
