// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nekobot/pkg/storage/ent/run"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunCreate is the builder for creating a Run entity.
type RunCreate struct {
	config
	mutation *RunMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *RunCreate) SetTaskID(v string) *RunCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableTaskID(v *string) *RunCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *RunCreate) SetTarget(v string) *RunCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *RunCreate) SetNillableTarget(v *string) *RunCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *RunCreate) SetAgentID(v string) *RunCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableAgentID(v *string) *RunCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetComputerID sets the "computer_id" field.
func (_c *RunCreate) SetComputerID(v string) *RunCreate {
	_c.mutation.SetComputerID(v)
	return _c
}

// SetNillableComputerID sets the "computer_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableComputerID(v *string) *RunCreate {
	if v != nil {
		_c.SetComputerID(*v)
	}
	return _c
}

// SetRuntimeProfileID sets the "runtime_profile_id" field.
func (_c *RunCreate) SetRuntimeProfileID(v string) *RunCreate {
	_c.mutation.SetRuntimeProfileID(v)
	return _c
}

// SetNillableRuntimeProfileID sets the "runtime_profile_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableRuntimeProfileID(v *string) *RunCreate {
	if v != nil {
		_c.SetRuntimeProfileID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RunCreate) SetStatus(v string) *RunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RunCreate) SetNillableStatus(v *string) *RunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLeaseID sets the "lease_id" field.
func (_c *RunCreate) SetLeaseID(v string) *RunCreate {
	_c.mutation.SetLeaseID(v)
	return _c
}

// SetNillableLeaseID sets the "lease_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableLeaseID(v *string) *RunCreate {
	if v != nil {
		_c.SetLeaseID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RunCreate) SetRequestID(v string) *RunCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableRequestID(v *string) *RunCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetInputMessageID sets the "input_message_id" field.
func (_c *RunCreate) SetInputMessageID(v string) *RunCreate {
	_c.mutation.SetInputMessageID(v)
	return _c
}

// SetNillableInputMessageID sets the "input_message_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableInputMessageID(v *string) *RunCreate {
	if v != nil {
		_c.SetInputMessageID(*v)
	}
	return _c
}

// SetLastSeenEventID sets the "last_seen_event_id" field.
func (_c *RunCreate) SetLastSeenEventID(v string) *RunCreate {
	_c.mutation.SetLastSeenEventID(v)
	return _c
}

// SetNillableLastSeenEventID sets the "last_seen_event_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableLastSeenEventID(v *string) *RunCreate {
	if v != nil {
		_c.SetLastSeenEventID(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *RunCreate) SetStartedAt(v time.Time) *RunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableStartedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RunCreate) SetUpdatedAt(v time.Time) *RunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableUpdatedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *RunCreate) SetCompletedAt(v time.Time) *RunCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableCompletedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *RunCreate) SetError(v string) *RunCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *RunCreate) SetNillableError(v *string) *RunCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *RunCreate) SetSummary(v string) *RunCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *RunCreate) SetNillableSummary(v *string) *RunCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *RunCreate) SetState(v string) *RunCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *RunCreate) SetNillableState(v *string) *RunCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RunCreate) SetTenantID(v string) *RunCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableTenantID(v *string) *RunCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *RunCreate) SetOwnerUserID(v string) *RunCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *RunCreate) SetNillableOwnerUserID(v *string) *RunCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *RunCreate) SetVisibility(v run.Visibility) *RunCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *RunCreate) SetNillableVisibility(v *run.Visibility) *RunCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RunCreate) SetID(v string) *RunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RunCreate) SetNillableID(v *string) *RunCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RunMutation object of the builder.
func (_c *RunCreate) Mutation() *RunMutation {
	return _c.mutation
}

// Save creates the Run in the database.
func (_c *RunCreate) Save(ctx context.Context) (*Run, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunCreate) SaveX(ctx context.Context) *Run {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunCreate) defaults() {
	if _, ok := _c.mutation.TaskID(); !ok {
		v := run.DefaultTaskID
		_c.mutation.SetTaskID(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := run.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		v := run.DefaultAgentID
		_c.mutation.SetAgentID(v)
	}
	if _, ok := _c.mutation.ComputerID(); !ok {
		v := run.DefaultComputerID
		_c.mutation.SetComputerID(v)
	}
	if _, ok := _c.mutation.RuntimeProfileID(); !ok {
		v := run.DefaultRuntimeProfileID
		_c.mutation.SetRuntimeProfileID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := run.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LeaseID(); !ok {
		v := run.DefaultLeaseID
		_c.mutation.SetLeaseID(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := run.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.InputMessageID(); !ok {
		v := run.DefaultInputMessageID
		_c.mutation.SetInputMessageID(v)
	}
	if _, ok := _c.mutation.LastSeenEventID(); !ok {
		v := run.DefaultLastSeenEventID
		_c.mutation.SetLastSeenEventID(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := run.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := run.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := run.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := run.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := run.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := run.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		v := run.DefaultOwnerUserID
		_c.mutation.SetOwnerUserID(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := run.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := run.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Run.task_id"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Run.target"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Run.agent_id"`)}
	}
	if _, ok := _c.mutation.ComputerID(); !ok {
		return &ValidationError{Name: "computer_id", err: errors.New(`ent: missing required field "Run.computer_id"`)}
	}
	if _, ok := _c.mutation.RuntimeProfileID(); !ok {
		return &ValidationError{Name: "runtime_profile_id", err: errors.New(`ent: missing required field "Run.runtime_profile_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Run.status"`)}
	}
	if _, ok := _c.mutation.LeaseID(); !ok {
		return &ValidationError{Name: "lease_id", err: errors.New(`ent: missing required field "Run.lease_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "Run.request_id"`)}
	}
	if _, ok := _c.mutation.InputMessageID(); !ok {
		return &ValidationError{Name: "input_message_id", err: errors.New(`ent: missing required field "Run.input_message_id"`)}
	}
	if _, ok := _c.mutation.LastSeenEventID(); !ok {
		return &ValidationError{Name: "last_seen_event_id", err: errors.New(`ent: missing required field "Run.last_seen_event_id"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Run.started_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Run.updated_at"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "Run.error"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Run.summary"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Run.state"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Run.tenant_id"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Run.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Run.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := run.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Run.visibility": %w`, err)}
		}
	}
	return nil
}

func (_c *RunCreate) sqlSave(ctx context.Context) (*Run, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Run.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunCreate) createSpec() (*Run, *sqlgraph.CreateSpec) {
	var (
		_node = &Run{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(run.Table, sqlgraph.NewFieldSpec(run.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(run.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(run.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(run.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.ComputerID(); ok {
		_spec.SetField(run.FieldComputerID, field.TypeString, value)
		_node.ComputerID = value
	}
	if value, ok := _c.mutation.RuntimeProfileID(); ok {
		_spec.SetField(run.FieldRuntimeProfileID, field.TypeString, value)
		_node.RuntimeProfileID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LeaseID(); ok {
		_spec.SetField(run.FieldLeaseID, field.TypeString, value)
		_node.LeaseID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(run.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.InputMessageID(); ok {
		_spec.SetField(run.FieldInputMessageID, field.TypeString, value)
		_node.InputMessageID = value
	}
	if value, ok := _c.mutation.LastSeenEventID(); ok {
		_spec.SetField(run.FieldLastSeenEventID, field.TypeString, value)
		_node.LastSeenEventID = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(run.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(run.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(run.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(run.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(run.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(run.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(run.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	return _node, _spec
}

// RunCreateBulk is the builder for creating many Run entities in bulk.
type RunCreateBulk struct {
	config
	err      error
	builders []*RunCreate
}

// Save creates the Run entities in the database.
func (_c *RunCreateBulk) Save(ctx context.Context) ([]*Run, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Run, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunCreateBulk) SaveX(ctx context.Context) []*Run {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
