// Code generated by ent, DO NOT EDIT.

package ent

import (
	"nekobot/pkg/storage/ent/accountbinding"
	"nekobot/pkg/storage/ent/agentruntime"
	"nekobot/pkg/storage/ent/attachtoken"
	"nekobot/pkg/storage/ent/channelaccount"
	"nekobot/pkg/storage/ent/configsection"
	"nekobot/pkg/storage/ent/cronjob"
	"nekobot/pkg/storage/ent/membership"
	"nekobot/pkg/storage/ent/modelcatalog"
	"nekobot/pkg/storage/ent/modelroute"
	"nekobot/pkg/storage/ent/permissionrule"
	"nekobot/pkg/storage/ent/prompt"
	"nekobot/pkg/storage/ent/promptbinding"
	"nekobot/pkg/storage/ent/provider"
	"nekobot/pkg/storage/ent/schema"
	"nekobot/pkg/storage/ent/tenant"
	"nekobot/pkg/storage/ent/toolevent"
	"nekobot/pkg/storage/ent/toolsession"
	"nekobot/pkg/storage/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountbindingFields := schema.AccountBinding{}.Fields()
	_ = accountbindingFields
	// accountbindingDescChannelAccountID is the schema descriptor for channel_account_id field.
	accountbindingDescChannelAccountID := accountbindingFields[1].Descriptor()
	// accountbinding.ChannelAccountIDValidator is a validator for the "channel_account_id" field. It is called by the builders before save.
	accountbinding.ChannelAccountIDValidator = accountbindingDescChannelAccountID.Validators[0].(func(string) error)
	// accountbindingDescAgentRuntimeID is the schema descriptor for agent_runtime_id field.
	accountbindingDescAgentRuntimeID := accountbindingFields[2].Descriptor()
	// accountbinding.AgentRuntimeIDValidator is a validator for the "agent_runtime_id" field. It is called by the builders before save.
	accountbinding.AgentRuntimeIDValidator = accountbindingDescAgentRuntimeID.Validators[0].(func(string) error)
	// accountbindingDescEnabled is the schema descriptor for enabled field.
	accountbindingDescEnabled := accountbindingFields[4].Descriptor()
	// accountbinding.DefaultEnabled holds the default value on creation for the enabled field.
	accountbinding.DefaultEnabled = accountbindingDescEnabled.Default.(bool)
	// accountbindingDescAllowPublicReply is the schema descriptor for allow_public_reply field.
	accountbindingDescAllowPublicReply := accountbindingFields[5].Descriptor()
	// accountbinding.DefaultAllowPublicReply holds the default value on creation for the allow_public_reply field.
	accountbinding.DefaultAllowPublicReply = accountbindingDescAllowPublicReply.Default.(bool)
	// accountbindingDescReplyLabel is the schema descriptor for reply_label field.
	accountbindingDescReplyLabel := accountbindingFields[6].Descriptor()
	// accountbinding.DefaultReplyLabel holds the default value on creation for the reply_label field.
	accountbinding.DefaultReplyLabel = accountbindingDescReplyLabel.Default.(string)
	// accountbindingDescPriority is the schema descriptor for priority field.
	accountbindingDescPriority := accountbindingFields[7].Descriptor()
	// accountbinding.DefaultPriority holds the default value on creation for the priority field.
	accountbinding.DefaultPriority = accountbindingDescPriority.Default.(int)
	// accountbindingDescMetadataJSON is the schema descriptor for metadata_json field.
	accountbindingDescMetadataJSON := accountbindingFields[8].Descriptor()
	// accountbinding.DefaultMetadataJSON holds the default value on creation for the metadata_json field.
	accountbinding.DefaultMetadataJSON = accountbindingDescMetadataJSON.Default.(string)
	// accountbindingDescCreatedAt is the schema descriptor for created_at field.
	accountbindingDescCreatedAt := accountbindingFields[9].Descriptor()
	// accountbinding.DefaultCreatedAt holds the default value on creation for the created_at field.
	accountbinding.DefaultCreatedAt = accountbindingDescCreatedAt.Default.(func() time.Time)
	// accountbindingDescUpdatedAt is the schema descriptor for updated_at field.
	accountbindingDescUpdatedAt := accountbindingFields[10].Descriptor()
	// accountbinding.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	accountbinding.DefaultUpdatedAt = accountbindingDescUpdatedAt.Default.(func() time.Time)
	// accountbinding.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	accountbinding.UpdateDefaultUpdatedAt = accountbindingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountbindingDescID is the schema descriptor for id field.
	accountbindingDescID := accountbindingFields[0].Descriptor()
	// accountbinding.DefaultID holds the default value on creation for the id field.
	accountbinding.DefaultID = accountbindingDescID.Default.(func() string)
	agentruntimeFields := schema.AgentRuntime{}.Fields()
	_ = agentruntimeFields
	// agentruntimeDescName is the schema descriptor for name field.
	agentruntimeDescName := agentruntimeFields[1].Descriptor()
	// agentruntime.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agentruntime.NameValidator = agentruntimeDescName.Validators[0].(func(string) error)
	// agentruntimeDescDisplayName is the schema descriptor for display_name field.
	agentruntimeDescDisplayName := agentruntimeFields[2].Descriptor()
	// agentruntime.DefaultDisplayName holds the default value on creation for the display_name field.
	agentruntime.DefaultDisplayName = agentruntimeDescDisplayName.Default.(string)
	// agentruntimeDescDescription is the schema descriptor for description field.
	agentruntimeDescDescription := agentruntimeFields[3].Descriptor()
	// agentruntime.DefaultDescription holds the default value on creation for the description field.
	agentruntime.DefaultDescription = agentruntimeDescDescription.Default.(string)
	// agentruntimeDescEnabled is the schema descriptor for enabled field.
	agentruntimeDescEnabled := agentruntimeFields[4].Descriptor()
	// agentruntime.DefaultEnabled holds the default value on creation for the enabled field.
	agentruntime.DefaultEnabled = agentruntimeDescEnabled.Default.(bool)
	// agentruntimeDescProvider is the schema descriptor for provider field.
	agentruntimeDescProvider := agentruntimeFields[5].Descriptor()
	// agentruntime.DefaultProvider holds the default value on creation for the provider field.
	agentruntime.DefaultProvider = agentruntimeDescProvider.Default.(string)
	// agentruntimeDescModel is the schema descriptor for model field.
	agentruntimeDescModel := agentruntimeFields[6].Descriptor()
	// agentruntime.DefaultModel holds the default value on creation for the model field.
	agentruntime.DefaultModel = agentruntimeDescModel.Default.(string)
	// agentruntimeDescPromptID is the schema descriptor for prompt_id field.
	agentruntimeDescPromptID := agentruntimeFields[7].Descriptor()
	// agentruntime.DefaultPromptID holds the default value on creation for the prompt_id field.
	agentruntime.DefaultPromptID = agentruntimeDescPromptID.Default.(string)
	// agentruntimeDescSkillsJSON is the schema descriptor for skills_json field.
	agentruntimeDescSkillsJSON := agentruntimeFields[8].Descriptor()
	// agentruntime.DefaultSkillsJSON holds the default value on creation for the skills_json field.
	agentruntime.DefaultSkillsJSON = agentruntimeDescSkillsJSON.Default.(string)
	// agentruntimeDescToolsJSON is the schema descriptor for tools_json field.
	agentruntimeDescToolsJSON := agentruntimeFields[9].Descriptor()
	// agentruntime.DefaultToolsJSON holds the default value on creation for the tools_json field.
	agentruntime.DefaultToolsJSON = agentruntimeDescToolsJSON.Default.(string)
	// agentruntimeDescPolicyJSON is the schema descriptor for policy_json field.
	agentruntimeDescPolicyJSON := agentruntimeFields[10].Descriptor()
	// agentruntime.DefaultPolicyJSON holds the default value on creation for the policy_json field.
	agentruntime.DefaultPolicyJSON = agentruntimeDescPolicyJSON.Default.(string)
	// agentruntimeDescCreatedAt is the schema descriptor for created_at field.
	agentruntimeDescCreatedAt := agentruntimeFields[11].Descriptor()
	// agentruntime.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentruntime.DefaultCreatedAt = agentruntimeDescCreatedAt.Default.(func() time.Time)
	// agentruntimeDescUpdatedAt is the schema descriptor for updated_at field.
	agentruntimeDescUpdatedAt := agentruntimeFields[12].Descriptor()
	// agentruntime.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentruntime.DefaultUpdatedAt = agentruntimeDescUpdatedAt.Default.(func() time.Time)
	// agentruntime.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentruntime.UpdateDefaultUpdatedAt = agentruntimeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentruntimeDescID is the schema descriptor for id field.
	agentruntimeDescID := agentruntimeFields[0].Descriptor()
	// agentruntime.DefaultID holds the default value on creation for the id field.
	agentruntime.DefaultID = agentruntimeDescID.Default.(func() string)
	attachtokenFields := schema.AttachToken{}.Fields()
	_ = attachtokenFields
	// attachtokenDescOwner is the schema descriptor for owner field.
	attachtokenDescOwner := attachtokenFields[3].Descriptor()
	// attachtoken.DefaultOwner holds the default value on creation for the owner field.
	attachtoken.DefaultOwner = attachtokenDescOwner.Default.(string)
	// attachtokenDescCreatedAt is the schema descriptor for created_at field.
	attachtokenDescCreatedAt := attachtokenFields[6].Descriptor()
	// attachtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachtoken.DefaultCreatedAt = attachtokenDescCreatedAt.Default.(func() time.Time)
	// attachtokenDescID is the schema descriptor for id field.
	attachtokenDescID := attachtokenFields[0].Descriptor()
	// attachtoken.DefaultID holds the default value on creation for the id field.
	attachtoken.DefaultID = attachtokenDescID.Default.(func() string)
	channelaccountFields := schema.ChannelAccount{}.Fields()
	_ = channelaccountFields
	// channelaccountDescChannelType is the schema descriptor for channel_type field.
	channelaccountDescChannelType := channelaccountFields[1].Descriptor()
	// channelaccount.ChannelTypeValidator is a validator for the "channel_type" field. It is called by the builders before save.
	channelaccount.ChannelTypeValidator = channelaccountDescChannelType.Validators[0].(func(string) error)
	// channelaccountDescAccountKey is the schema descriptor for account_key field.
	channelaccountDescAccountKey := channelaccountFields[2].Descriptor()
	// channelaccount.AccountKeyValidator is a validator for the "account_key" field. It is called by the builders before save.
	channelaccount.AccountKeyValidator = channelaccountDescAccountKey.Validators[0].(func(string) error)
	// channelaccountDescDisplayName is the schema descriptor for display_name field.
	channelaccountDescDisplayName := channelaccountFields[3].Descriptor()
	// channelaccount.DefaultDisplayName holds the default value on creation for the display_name field.
	channelaccount.DefaultDisplayName = channelaccountDescDisplayName.Default.(string)
	// channelaccountDescDescription is the schema descriptor for description field.
	channelaccountDescDescription := channelaccountFields[4].Descriptor()
	// channelaccount.DefaultDescription holds the default value on creation for the description field.
	channelaccount.DefaultDescription = channelaccountDescDescription.Default.(string)
	// channelaccountDescEnabled is the schema descriptor for enabled field.
	channelaccountDescEnabled := channelaccountFields[5].Descriptor()
	// channelaccount.DefaultEnabled holds the default value on creation for the enabled field.
	channelaccount.DefaultEnabled = channelaccountDescEnabled.Default.(bool)
	// channelaccountDescConfigJSON is the schema descriptor for config_json field.
	channelaccountDescConfigJSON := channelaccountFields[6].Descriptor()
	// channelaccount.DefaultConfigJSON holds the default value on creation for the config_json field.
	channelaccount.DefaultConfigJSON = channelaccountDescConfigJSON.Default.(string)
	// channelaccountDescMetadataJSON is the schema descriptor for metadata_json field.
	channelaccountDescMetadataJSON := channelaccountFields[7].Descriptor()
	// channelaccount.DefaultMetadataJSON holds the default value on creation for the metadata_json field.
	channelaccount.DefaultMetadataJSON = channelaccountDescMetadataJSON.Default.(string)
	// channelaccountDescCreatedAt is the schema descriptor for created_at field.
	channelaccountDescCreatedAt := channelaccountFields[8].Descriptor()
	// channelaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelaccount.DefaultCreatedAt = channelaccountDescCreatedAt.Default.(func() time.Time)
	// channelaccountDescUpdatedAt is the schema descriptor for updated_at field.
	channelaccountDescUpdatedAt := channelaccountFields[9].Descriptor()
	// channelaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channelaccount.DefaultUpdatedAt = channelaccountDescUpdatedAt.Default.(func() time.Time)
	// channelaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channelaccount.UpdateDefaultUpdatedAt = channelaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelaccountDescID is the schema descriptor for id field.
	channelaccountDescID := channelaccountFields[0].Descriptor()
	// channelaccount.DefaultID holds the default value on creation for the id field.
	channelaccount.DefaultID = channelaccountDescID.Default.(func() string)
	configsectionFields := schema.ConfigSection{}.Fields()
	_ = configsectionFields
	// configsectionDescSection is the schema descriptor for section field.
	configsectionDescSection := configsectionFields[0].Descriptor()
	// configsection.SectionValidator is a validator for the "section" field. It is called by the builders before save.
	configsection.SectionValidator = configsectionDescSection.Validators[0].(func(string) error)
	// configsectionDescPayloadJSON is the schema descriptor for payload_json field.
	configsectionDescPayloadJSON := configsectionFields[1].Descriptor()
	// configsection.DefaultPayloadJSON holds the default value on creation for the payload_json field.
	configsection.DefaultPayloadJSON = configsectionDescPayloadJSON.Default.(string)
	// configsectionDescCreatedAt is the schema descriptor for created_at field.
	configsectionDescCreatedAt := configsectionFields[2].Descriptor()
	// configsection.DefaultCreatedAt holds the default value on creation for the created_at field.
	configsection.DefaultCreatedAt = configsectionDescCreatedAt.Default.(func() time.Time)
	// configsectionDescUpdatedAt is the schema descriptor for updated_at field.
	configsectionDescUpdatedAt := configsectionFields[3].Descriptor()
	// configsection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configsection.DefaultUpdatedAt = configsectionDescUpdatedAt.Default.(func() time.Time)
	// configsection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configsection.UpdateDefaultUpdatedAt = configsectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	cronjobFields := schema.CronJob{}.Fields()
	_ = cronjobFields
	// cronjobDescName is the schema descriptor for name field.
	cronjobDescName := cronjobFields[1].Descriptor()
	// cronjob.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cronjob.NameValidator = cronjobDescName.Validators[0].(func(string) error)
	// cronjobDescScheduleKind is the schema descriptor for schedule_kind field.
	cronjobDescScheduleKind := cronjobFields[2].Descriptor()
	// cronjob.DefaultScheduleKind holds the default value on creation for the schedule_kind field.
	cronjob.DefaultScheduleKind = cronjobDescScheduleKind.Default.(string)
	// cronjobDescSchedule is the schema descriptor for schedule field.
	cronjobDescSchedule := cronjobFields[3].Descriptor()
	// cronjob.DefaultSchedule holds the default value on creation for the schedule field.
	cronjob.DefaultSchedule = cronjobDescSchedule.Default.(string)
	// cronjobDescEveryDuration is the schema descriptor for every_duration field.
	cronjobDescEveryDuration := cronjobFields[5].Descriptor()
	// cronjob.DefaultEveryDuration holds the default value on creation for the every_duration field.
	cronjob.DefaultEveryDuration = cronjobDescEveryDuration.Default.(string)
	// cronjobDescPrompt is the schema descriptor for prompt field.
	cronjobDescPrompt := cronjobFields[6].Descriptor()
	// cronjob.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	cronjob.PromptValidator = cronjobDescPrompt.Validators[0].(func(string) error)
	// cronjobDescProvider is the schema descriptor for provider field.
	cronjobDescProvider := cronjobFields[7].Descriptor()
	// cronjob.DefaultProvider holds the default value on creation for the provider field.
	cronjob.DefaultProvider = cronjobDescProvider.Default.(string)
	// cronjobDescModel is the schema descriptor for model field.
	cronjobDescModel := cronjobFields[8].Descriptor()
	// cronjob.DefaultModel holds the default value on creation for the model field.
	cronjob.DefaultModel = cronjobDescModel.Default.(string)
	// cronjobDescFallbackJSON is the schema descriptor for fallback_json field.
	cronjobDescFallbackJSON := cronjobFields[9].Descriptor()
	// cronjob.DefaultFallbackJSON holds the default value on creation for the fallback_json field.
	cronjob.DefaultFallbackJSON = cronjobDescFallbackJSON.Default.(string)
	// cronjobDescEnabled is the schema descriptor for enabled field.
	cronjobDescEnabled := cronjobFields[10].Descriptor()
	// cronjob.DefaultEnabled holds the default value on creation for the enabled field.
	cronjob.DefaultEnabled = cronjobDescEnabled.Default.(bool)
	// cronjobDescDeleteAfterRun is the schema descriptor for delete_after_run field.
	cronjobDescDeleteAfterRun := cronjobFields[11].Descriptor()
	// cronjob.DefaultDeleteAfterRun holds the default value on creation for the delete_after_run field.
	cronjob.DefaultDeleteAfterRun = cronjobDescDeleteAfterRun.Default.(bool)
	// cronjobDescCreatedAt is the schema descriptor for created_at field.
	cronjobDescCreatedAt := cronjobFields[12].Descriptor()
	// cronjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	cronjob.DefaultCreatedAt = cronjobDescCreatedAt.Default.(func() time.Time)
	// cronjobDescRunCount is the schema descriptor for run_count field.
	cronjobDescRunCount := cronjobFields[15].Descriptor()
	// cronjob.DefaultRunCount holds the default value on creation for the run_count field.
	cronjob.DefaultRunCount = cronjobDescRunCount.Default.(int)
	// cronjobDescLastError is the schema descriptor for last_error field.
	cronjobDescLastError := cronjobFields[16].Descriptor()
	// cronjob.DefaultLastError holds the default value on creation for the last_error field.
	cronjob.DefaultLastError = cronjobDescLastError.Default.(string)
	// cronjobDescLastSuccess is the schema descriptor for last_success field.
	cronjobDescLastSuccess := cronjobFields[17].Descriptor()
	// cronjob.DefaultLastSuccess holds the default value on creation for the last_success field.
	cronjob.DefaultLastSuccess = cronjobDescLastSuccess.Default.(bool)
	// cronjobDescID is the schema descriptor for id field.
	cronjobDescID := cronjobFields[0].Descriptor()
	// cronjob.DefaultID holds the default value on creation for the id field.
	cronjob.DefaultID = cronjobDescID.Default.(func() string)
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescUserID is the schema descriptor for user_id field.
	membershipDescUserID := membershipFields[1].Descriptor()
	// membership.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	membership.UserIDValidator = membershipDescUserID.Validators[0].(func(string) error)
	// membershipDescTenantID is the schema descriptor for tenant_id field.
	membershipDescTenantID := membershipFields[2].Descriptor()
	// membership.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	membership.TenantIDValidator = membershipDescTenantID.Validators[0].(func(string) error)
	// membershipDescRole is the schema descriptor for role field.
	membershipDescRole := membershipFields[3].Descriptor()
	// membership.DefaultRole holds the default value on creation for the role field.
	membership.DefaultRole = membershipDescRole.Default.(string)
	// membershipDescEnabled is the schema descriptor for enabled field.
	membershipDescEnabled := membershipFields[4].Descriptor()
	// membership.DefaultEnabled holds the default value on creation for the enabled field.
	membership.DefaultEnabled = membershipDescEnabled.Default.(bool)
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipFields[5].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescUpdatedAt is the schema descriptor for updated_at field.
	membershipDescUpdatedAt := membershipFields[6].Descriptor()
	// membership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membership.DefaultUpdatedAt = membershipDescUpdatedAt.Default.(func() time.Time)
	// membership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membership.UpdateDefaultUpdatedAt = membershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipFields[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() string)
	modelcatalogFields := schema.ModelCatalog{}.Fields()
	_ = modelcatalogFields
	// modelcatalogDescModelID is the schema descriptor for model_id field.
	modelcatalogDescModelID := modelcatalogFields[1].Descriptor()
	// modelcatalog.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	modelcatalog.ModelIDValidator = modelcatalogDescModelID.Validators[0].(func(string) error)
	// modelcatalogDescDisplayName is the schema descriptor for display_name field.
	modelcatalogDescDisplayName := modelcatalogFields[2].Descriptor()
	// modelcatalog.DefaultDisplayName holds the default value on creation for the display_name field.
	modelcatalog.DefaultDisplayName = modelcatalogDescDisplayName.Default.(string)
	// modelcatalogDescDeveloper is the schema descriptor for developer field.
	modelcatalogDescDeveloper := modelcatalogFields[3].Descriptor()
	// modelcatalog.DefaultDeveloper holds the default value on creation for the developer field.
	modelcatalog.DefaultDeveloper = modelcatalogDescDeveloper.Default.(string)
	// modelcatalogDescFamily is the schema descriptor for family field.
	modelcatalogDescFamily := modelcatalogFields[4].Descriptor()
	// modelcatalog.DefaultFamily holds the default value on creation for the family field.
	modelcatalog.DefaultFamily = modelcatalogDescFamily.Default.(string)
	// modelcatalogDescType is the schema descriptor for type field.
	modelcatalogDescType := modelcatalogFields[5].Descriptor()
	// modelcatalog.DefaultType holds the default value on creation for the type field.
	modelcatalog.DefaultType = modelcatalogDescType.Default.(string)
	// modelcatalogDescCapabilitiesJSON is the schema descriptor for capabilities_json field.
	modelcatalogDescCapabilitiesJSON := modelcatalogFields[6].Descriptor()
	// modelcatalog.DefaultCapabilitiesJSON holds the default value on creation for the capabilities_json field.
	modelcatalog.DefaultCapabilitiesJSON = modelcatalogDescCapabilitiesJSON.Default.(string)
	// modelcatalogDescCatalogSource is the schema descriptor for catalog_source field.
	modelcatalogDescCatalogSource := modelcatalogFields[7].Descriptor()
	// modelcatalog.DefaultCatalogSource holds the default value on creation for the catalog_source field.
	modelcatalog.DefaultCatalogSource = modelcatalogDescCatalogSource.Default.(string)
	// modelcatalogDescEnabled is the schema descriptor for enabled field.
	modelcatalogDescEnabled := modelcatalogFields[8].Descriptor()
	// modelcatalog.DefaultEnabled holds the default value on creation for the enabled field.
	modelcatalog.DefaultEnabled = modelcatalogDescEnabled.Default.(bool)
	// modelcatalogDescCreatedAt is the schema descriptor for created_at field.
	modelcatalogDescCreatedAt := modelcatalogFields[9].Descriptor()
	// modelcatalog.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelcatalog.DefaultCreatedAt = modelcatalogDescCreatedAt.Default.(func() time.Time)
	// modelcatalogDescUpdatedAt is the schema descriptor for updated_at field.
	modelcatalogDescUpdatedAt := modelcatalogFields[10].Descriptor()
	// modelcatalog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelcatalog.DefaultUpdatedAt = modelcatalogDescUpdatedAt.Default.(func() time.Time)
	// modelcatalog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelcatalog.UpdateDefaultUpdatedAt = modelcatalogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// modelcatalogDescID is the schema descriptor for id field.
	modelcatalogDescID := modelcatalogFields[0].Descriptor()
	// modelcatalog.DefaultID holds the default value on creation for the id field.
	modelcatalog.DefaultID = modelcatalogDescID.Default.(func() string)
	modelrouteFields := schema.ModelRoute{}.Fields()
	_ = modelrouteFields
	// modelrouteDescModelID is the schema descriptor for model_id field.
	modelrouteDescModelID := modelrouteFields[1].Descriptor()
	// modelroute.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	modelroute.ModelIDValidator = modelrouteDescModelID.Validators[0].(func(string) error)
	// modelrouteDescProviderName is the schema descriptor for provider_name field.
	modelrouteDescProviderName := modelrouteFields[2].Descriptor()
	// modelroute.ProviderNameValidator is a validator for the "provider_name" field. It is called by the builders before save.
	modelroute.ProviderNameValidator = modelrouteDescProviderName.Validators[0].(func(string) error)
	// modelrouteDescEnabled is the schema descriptor for enabled field.
	modelrouteDescEnabled := modelrouteFields[3].Descriptor()
	// modelroute.DefaultEnabled holds the default value on creation for the enabled field.
	modelroute.DefaultEnabled = modelrouteDescEnabled.Default.(bool)
	// modelrouteDescIsDefault is the schema descriptor for is_default field.
	modelrouteDescIsDefault := modelrouteFields[4].Descriptor()
	// modelroute.DefaultIsDefault holds the default value on creation for the is_default field.
	modelroute.DefaultIsDefault = modelrouteDescIsDefault.Default.(bool)
	// modelrouteDescWeightOverride is the schema descriptor for weight_override field.
	modelrouteDescWeightOverride := modelrouteFields[5].Descriptor()
	// modelroute.DefaultWeightOverride holds the default value on creation for the weight_override field.
	modelroute.DefaultWeightOverride = modelrouteDescWeightOverride.Default.(int)
	// modelrouteDescAliasesJSON is the schema descriptor for aliases_json field.
	modelrouteDescAliasesJSON := modelrouteFields[6].Descriptor()
	// modelroute.DefaultAliasesJSON holds the default value on creation for the aliases_json field.
	modelroute.DefaultAliasesJSON = modelrouteDescAliasesJSON.Default.(string)
	// modelrouteDescRegexRulesJSON is the schema descriptor for regex_rules_json field.
	modelrouteDescRegexRulesJSON := modelrouteFields[7].Descriptor()
	// modelroute.DefaultRegexRulesJSON holds the default value on creation for the regex_rules_json field.
	modelroute.DefaultRegexRulesJSON = modelrouteDescRegexRulesJSON.Default.(string)
	// modelrouteDescMetadataJSON is the schema descriptor for metadata_json field.
	modelrouteDescMetadataJSON := modelrouteFields[8].Descriptor()
	// modelroute.DefaultMetadataJSON holds the default value on creation for the metadata_json field.
	modelroute.DefaultMetadataJSON = modelrouteDescMetadataJSON.Default.(string)
	// modelrouteDescCreatedAt is the schema descriptor for created_at field.
	modelrouteDescCreatedAt := modelrouteFields[9].Descriptor()
	// modelroute.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelroute.DefaultCreatedAt = modelrouteDescCreatedAt.Default.(func() time.Time)
	// modelrouteDescUpdatedAt is the schema descriptor for updated_at field.
	modelrouteDescUpdatedAt := modelrouteFields[10].Descriptor()
	// modelroute.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelroute.DefaultUpdatedAt = modelrouteDescUpdatedAt.Default.(func() time.Time)
	// modelroute.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelroute.UpdateDefaultUpdatedAt = modelrouteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// modelrouteDescID is the schema descriptor for id field.
	modelrouteDescID := modelrouteFields[0].Descriptor()
	// modelroute.DefaultID holds the default value on creation for the id field.
	modelroute.DefaultID = modelrouteDescID.Default.(func() string)
	permissionruleFields := schema.PermissionRule{}.Fields()
	_ = permissionruleFields
	// permissionruleDescEnabled is the schema descriptor for enabled field.
	permissionruleDescEnabled := permissionruleFields[1].Descriptor()
	// permissionrule.DefaultEnabled holds the default value on creation for the enabled field.
	permissionrule.DefaultEnabled = permissionruleDescEnabled.Default.(bool)
	// permissionruleDescPriority is the schema descriptor for priority field.
	permissionruleDescPriority := permissionruleFields[2].Descriptor()
	// permissionrule.DefaultPriority holds the default value on creation for the priority field.
	permissionrule.DefaultPriority = permissionruleDescPriority.Default.(int)
	// permissionruleDescToolName is the schema descriptor for tool_name field.
	permissionruleDescToolName := permissionruleFields[3].Descriptor()
	// permissionrule.ToolNameValidator is a validator for the "tool_name" field. It is called by the builders before save.
	permissionrule.ToolNameValidator = permissionruleDescToolName.Validators[0].(func(string) error)
	// permissionruleDescSessionID is the schema descriptor for session_id field.
	permissionruleDescSessionID := permissionruleFields[4].Descriptor()
	// permissionrule.DefaultSessionID holds the default value on creation for the session_id field.
	permissionrule.DefaultSessionID = permissionruleDescSessionID.Default.(string)
	// permissionruleDescRuntimeID is the schema descriptor for runtime_id field.
	permissionruleDescRuntimeID := permissionruleFields[5].Descriptor()
	// permissionrule.DefaultRuntimeID holds the default value on creation for the runtime_id field.
	permissionrule.DefaultRuntimeID = permissionruleDescRuntimeID.Default.(string)
	// permissionruleDescAction is the schema descriptor for action field.
	permissionruleDescAction := permissionruleFields[6].Descriptor()
	// permissionrule.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permissionrule.ActionValidator = permissionruleDescAction.Validators[0].(func(string) error)
	// permissionruleDescDescription is the schema descriptor for description field.
	permissionruleDescDescription := permissionruleFields[7].Descriptor()
	// permissionrule.DefaultDescription holds the default value on creation for the description field.
	permissionrule.DefaultDescription = permissionruleDescDescription.Default.(string)
	// permissionruleDescCreatedAt is the schema descriptor for created_at field.
	permissionruleDescCreatedAt := permissionruleFields[8].Descriptor()
	// permissionrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	permissionrule.DefaultCreatedAt = permissionruleDescCreatedAt.Default.(func() time.Time)
	// permissionruleDescUpdatedAt is the schema descriptor for updated_at field.
	permissionruleDescUpdatedAt := permissionruleFields[9].Descriptor()
	// permissionrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permissionrule.DefaultUpdatedAt = permissionruleDescUpdatedAt.Default.(func() time.Time)
	// permissionrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permissionrule.UpdateDefaultUpdatedAt = permissionruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionruleDescID is the schema descriptor for id field.
	permissionruleDescID := permissionruleFields[0].Descriptor()
	// permissionrule.DefaultID holds the default value on creation for the id field.
	permissionrule.DefaultID = permissionruleDescID.Default.(func() string)
	promptFields := schema.Prompt{}.Fields()
	_ = promptFields
	// promptDescPromptKey is the schema descriptor for prompt_key field.
	promptDescPromptKey := promptFields[1].Descriptor()
	// prompt.PromptKeyValidator is a validator for the "prompt_key" field. It is called by the builders before save.
	prompt.PromptKeyValidator = promptDescPromptKey.Validators[0].(func(string) error)
	// promptDescName is the schema descriptor for name field.
	promptDescName := promptFields[2].Descriptor()
	// prompt.NameValidator is a validator for the "name" field. It is called by the builders before save.
	prompt.NameValidator = promptDescName.Validators[0].(func(string) error)
	// promptDescDescription is the schema descriptor for description field.
	promptDescDescription := promptFields[3].Descriptor()
	// prompt.DefaultDescription holds the default value on creation for the description field.
	prompt.DefaultDescription = promptDescDescription.Default.(string)
	// promptDescTemplate is the schema descriptor for template field.
	promptDescTemplate := promptFields[5].Descriptor()
	// prompt.TemplateValidator is a validator for the "template" field. It is called by the builders before save.
	prompt.TemplateValidator = promptDescTemplate.Validators[0].(func(string) error)
	// promptDescEnabled is the schema descriptor for enabled field.
	promptDescEnabled := promptFields[6].Descriptor()
	// prompt.DefaultEnabled holds the default value on creation for the enabled field.
	prompt.DefaultEnabled = promptDescEnabled.Default.(bool)
	// promptDescTagsJSON is the schema descriptor for tags_json field.
	promptDescTagsJSON := promptFields[7].Descriptor()
	// prompt.DefaultTagsJSON holds the default value on creation for the tags_json field.
	prompt.DefaultTagsJSON = promptDescTagsJSON.Default.(string)
	// promptDescCreatedAt is the schema descriptor for created_at field.
	promptDescCreatedAt := promptFields[8].Descriptor()
	// prompt.DefaultCreatedAt holds the default value on creation for the created_at field.
	prompt.DefaultCreatedAt = promptDescCreatedAt.Default.(func() time.Time)
	// promptDescUpdatedAt is the schema descriptor for updated_at field.
	promptDescUpdatedAt := promptFields[9].Descriptor()
	// prompt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prompt.DefaultUpdatedAt = promptDescUpdatedAt.Default.(func() time.Time)
	// prompt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prompt.UpdateDefaultUpdatedAt = promptDescUpdatedAt.UpdateDefault.(func() time.Time)
	// promptDescID is the schema descriptor for id field.
	promptDescID := promptFields[0].Descriptor()
	// prompt.DefaultID holds the default value on creation for the id field.
	prompt.DefaultID = promptDescID.Default.(func() string)
	promptbindingFields := schema.PromptBinding{}.Fields()
	_ = promptbindingFields
	// promptbindingDescTarget is the schema descriptor for target field.
	promptbindingDescTarget := promptbindingFields[2].Descriptor()
	// promptbinding.DefaultTarget holds the default value on creation for the target field.
	promptbinding.DefaultTarget = promptbindingDescTarget.Default.(string)
	// promptbindingDescPromptID is the schema descriptor for prompt_id field.
	promptbindingDescPromptID := promptbindingFields[3].Descriptor()
	// promptbinding.PromptIDValidator is a validator for the "prompt_id" field. It is called by the builders before save.
	promptbinding.PromptIDValidator = promptbindingDescPromptID.Validators[0].(func(string) error)
	// promptbindingDescEnabled is the schema descriptor for enabled field.
	promptbindingDescEnabled := promptbindingFields[4].Descriptor()
	// promptbinding.DefaultEnabled holds the default value on creation for the enabled field.
	promptbinding.DefaultEnabled = promptbindingDescEnabled.Default.(bool)
	// promptbindingDescPriority is the schema descriptor for priority field.
	promptbindingDescPriority := promptbindingFields[5].Descriptor()
	// promptbinding.DefaultPriority holds the default value on creation for the priority field.
	promptbinding.DefaultPriority = promptbindingDescPriority.Default.(int)
	// promptbindingDescCreatedAt is the schema descriptor for created_at field.
	promptbindingDescCreatedAt := promptbindingFields[6].Descriptor()
	// promptbinding.DefaultCreatedAt holds the default value on creation for the created_at field.
	promptbinding.DefaultCreatedAt = promptbindingDescCreatedAt.Default.(func() time.Time)
	// promptbindingDescUpdatedAt is the schema descriptor for updated_at field.
	promptbindingDescUpdatedAt := promptbindingFields[7].Descriptor()
	// promptbinding.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	promptbinding.DefaultUpdatedAt = promptbindingDescUpdatedAt.Default.(func() time.Time)
	// promptbinding.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	promptbinding.UpdateDefaultUpdatedAt = promptbindingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// promptbindingDescID is the schema descriptor for id field.
	promptbindingDescID := promptbindingFields[0].Descriptor()
	// promptbinding.DefaultID holds the default value on creation for the id field.
	promptbinding.DefaultID = promptbindingDescID.Default.(func() string)
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescName is the schema descriptor for name field.
	providerDescName := providerFields[1].Descriptor()
	// provider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	provider.NameValidator = providerDescName.Validators[0].(func(string) error)
	// providerDescProviderKind is the schema descriptor for provider_kind field.
	providerDescProviderKind := providerFields[2].Descriptor()
	// provider.ProviderKindValidator is a validator for the "provider_kind" field. It is called by the builders before save.
	provider.ProviderKindValidator = providerDescProviderKind.Validators[0].(func(string) error)
	// providerDescAPIKey is the schema descriptor for api_key field.
	providerDescAPIKey := providerFields[3].Descriptor()
	// provider.DefaultAPIKey holds the default value on creation for the api_key field.
	provider.DefaultAPIKey = providerDescAPIKey.Default.(string)
	// providerDescAPIBase is the schema descriptor for api_base field.
	providerDescAPIBase := providerFields[4].Descriptor()
	// provider.DefaultAPIBase holds the default value on creation for the api_base field.
	provider.DefaultAPIBase = providerDescAPIBase.Default.(string)
	// providerDescProxy is the schema descriptor for proxy field.
	providerDescProxy := providerFields[5].Descriptor()
	// provider.DefaultProxy holds the default value on creation for the proxy field.
	provider.DefaultProxy = providerDescProxy.Default.(string)
	// providerDescDefaultWeight is the schema descriptor for default_weight field.
	providerDescDefaultWeight := providerFields[6].Descriptor()
	// provider.DefaultDefaultWeight holds the default value on creation for the default_weight field.
	provider.DefaultDefaultWeight = providerDescDefaultWeight.Default.(int)
	// providerDescEnabled is the schema descriptor for enabled field.
	providerDescEnabled := providerFields[7].Descriptor()
	// provider.DefaultEnabled holds the default value on creation for the enabled field.
	provider.DefaultEnabled = providerDescEnabled.Default.(bool)
	// providerDescDefaultTestModel is the schema descriptor for default_test_model field.
	providerDescDefaultTestModel := providerFields[8].Descriptor()
	// provider.DefaultDefaultTestModel holds the default value on creation for the default_test_model field.
	provider.DefaultDefaultTestModel = providerDescDefaultTestModel.Default.(string)
	// providerDescAPIFormat is the schema descriptor for api_format field.
	providerDescAPIFormat := providerFields[9].Descriptor()
	// provider.DefaultAPIFormat holds the default value on creation for the api_format field.
	provider.DefaultAPIFormat = providerDescAPIFormat.Default.(string)
	// providerDescTimeout is the schema descriptor for timeout field.
	providerDescTimeout := providerFields[10].Descriptor()
	// provider.DefaultTimeout holds the default value on creation for the timeout field.
	provider.DefaultTimeout = providerDescTimeout.Default.(int)
	// providerDescCreatedAt is the schema descriptor for created_at field.
	providerDescCreatedAt := providerFields[11].Descriptor()
	// provider.DefaultCreatedAt holds the default value on creation for the created_at field.
	provider.DefaultCreatedAt = providerDescCreatedAt.Default.(func() time.Time)
	// providerDescUpdatedAt is the schema descriptor for updated_at field.
	providerDescUpdatedAt := providerFields[12].Descriptor()
	// provider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	provider.DefaultUpdatedAt = providerDescUpdatedAt.Default.(func() time.Time)
	// provider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	provider.UpdateDefaultUpdatedAt = providerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// providerDescID is the schema descriptor for id field.
	providerDescID := providerFields[0].Descriptor()
	// provider.DefaultID holds the default value on creation for the id field.
	provider.DefaultID = providerDescID.Default.(func() string)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[1].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[2].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescEnabled is the schema descriptor for enabled field.
	tenantDescEnabled := tenantFields[3].Descriptor()
	// tenant.DefaultEnabled holds the default value on creation for the enabled field.
	tenant.DefaultEnabled = tenantDescEnabled.Default.(bool)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[4].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() string)
	tooleventFields := schema.ToolEvent{}.Fields()
	_ = tooleventFields
	// tooleventDescPayloadJSON is the schema descriptor for payload_json field.
	tooleventDescPayloadJSON := tooleventFields[3].Descriptor()
	// toolevent.DefaultPayloadJSON holds the default value on creation for the payload_json field.
	toolevent.DefaultPayloadJSON = tooleventDescPayloadJSON.Default.(string)
	// tooleventDescCreatedAt is the schema descriptor for created_at field.
	tooleventDescCreatedAt := tooleventFields[4].Descriptor()
	// toolevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolevent.DefaultCreatedAt = tooleventDescCreatedAt.Default.(func() time.Time)
	// tooleventDescID is the schema descriptor for id field.
	tooleventDescID := tooleventFields[0].Descriptor()
	// toolevent.DefaultID holds the default value on creation for the id field.
	toolevent.DefaultID = tooleventDescID.Default.(func() string)
	toolsessionFields := schema.ToolSession{}.Fields()
	_ = toolsessionFields
	// toolsessionDescOwner is the schema descriptor for owner field.
	toolsessionDescOwner := toolsessionFields[1].Descriptor()
	// toolsession.DefaultOwner holds the default value on creation for the owner field.
	toolsession.DefaultOwner = toolsessionDescOwner.Default.(string)
	// toolsessionDescSource is the schema descriptor for source field.
	toolsessionDescSource := toolsessionFields[2].Descriptor()
	// toolsession.DefaultSource holds the default value on creation for the source field.
	toolsession.DefaultSource = toolsessionDescSource.Default.(string)
	// toolsessionDescChannel is the schema descriptor for channel field.
	toolsessionDescChannel := toolsessionFields[3].Descriptor()
	// toolsession.DefaultChannel holds the default value on creation for the channel field.
	toolsession.DefaultChannel = toolsessionDescChannel.Default.(string)
	// toolsessionDescConversationKey is the schema descriptor for conversation_key field.
	toolsessionDescConversationKey := toolsessionFields[4].Descriptor()
	// toolsession.DefaultConversationKey holds the default value on creation for the conversation_key field.
	toolsession.DefaultConversationKey = toolsessionDescConversationKey.Default.(string)
	// toolsessionDescTool is the schema descriptor for tool field.
	toolsessionDescTool := toolsessionFields[5].Descriptor()
	// toolsession.DefaultTool holds the default value on creation for the tool field.
	toolsession.DefaultTool = toolsessionDescTool.Default.(string)
	// toolsessionDescTitle is the schema descriptor for title field.
	toolsessionDescTitle := toolsessionFields[6].Descriptor()
	// toolsession.DefaultTitle holds the default value on creation for the title field.
	toolsession.DefaultTitle = toolsessionDescTitle.Default.(string)
	// toolsessionDescCommand is the schema descriptor for command field.
	toolsessionDescCommand := toolsessionFields[7].Descriptor()
	// toolsession.DefaultCommand holds the default value on creation for the command field.
	toolsession.DefaultCommand = toolsessionDescCommand.Default.(string)
	// toolsessionDescWorkdir is the schema descriptor for workdir field.
	toolsessionDescWorkdir := toolsessionFields[8].Descriptor()
	// toolsession.DefaultWorkdir holds the default value on creation for the workdir field.
	toolsession.DefaultWorkdir = toolsessionDescWorkdir.Default.(string)
	// toolsessionDescState is the schema descriptor for state field.
	toolsessionDescState := toolsessionFields[9].Descriptor()
	// toolsession.DefaultState holds the default value on creation for the state field.
	toolsession.DefaultState = toolsessionDescState.Default.(string)
	// toolsessionDescAccessMode is the schema descriptor for access_mode field.
	toolsessionDescAccessMode := toolsessionFields[10].Descriptor()
	// toolsession.DefaultAccessMode holds the default value on creation for the access_mode field.
	toolsession.DefaultAccessMode = toolsessionDescAccessMode.Default.(string)
	// toolsessionDescAccessSecretHash is the schema descriptor for access_secret_hash field.
	toolsessionDescAccessSecretHash := toolsessionFields[11].Descriptor()
	// toolsession.DefaultAccessSecretHash holds the default value on creation for the access_secret_hash field.
	toolsession.DefaultAccessSecretHash = toolsessionDescAccessSecretHash.Default.(string)
	// toolsessionDescPinned is the schema descriptor for pinned field.
	toolsessionDescPinned := toolsessionFields[13].Descriptor()
	// toolsession.DefaultPinned holds the default value on creation for the pinned field.
	toolsession.DefaultPinned = toolsessionDescPinned.Default.(bool)
	// toolsessionDescLastActiveAt is the schema descriptor for last_active_at field.
	toolsessionDescLastActiveAt := toolsessionFields[14].Descriptor()
	// toolsession.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	toolsession.DefaultLastActiveAt = toolsessionDescLastActiveAt.Default.(func() time.Time)
	// toolsessionDescMetadataJSON is the schema descriptor for metadata_json field.
	toolsessionDescMetadataJSON := toolsessionFields[18].Descriptor()
	// toolsession.DefaultMetadataJSON holds the default value on creation for the metadata_json field.
	toolsession.DefaultMetadataJSON = toolsessionDescMetadataJSON.Default.(string)
	// toolsessionDescCreatedAt is the schema descriptor for created_at field.
	toolsessionDescCreatedAt := toolsessionFields[19].Descriptor()
	// toolsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolsession.DefaultCreatedAt = toolsessionDescCreatedAt.Default.(func() time.Time)
	// toolsessionDescUpdatedAt is the schema descriptor for updated_at field.
	toolsessionDescUpdatedAt := toolsessionFields[20].Descriptor()
	// toolsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	toolsession.DefaultUpdatedAt = toolsessionDescUpdatedAt.Default.(func() time.Time)
	// toolsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	toolsession.UpdateDefaultUpdatedAt = toolsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// toolsessionDescID is the schema descriptor for id field.
	toolsessionDescID := toolsessionFields[0].Descriptor()
	// toolsession.DefaultID holds the default value on creation for the id field.
	toolsession.DefaultID = toolsessionDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescEnabled is the schema descriptor for enabled field.
	userDescEnabled := userFields[5].Descriptor()
	// user.DefaultEnabled holds the default value on creation for the enabled field.
	user.DefaultEnabled = userDescEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
