// Code generated by ent, DO NOT EDIT.

package idempotencyrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the idempotencyrecord type in the database.
	Label = "idempotency_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCallerKind holds the string denoting the caller_kind field in the database.
	FieldCallerKind = "caller_kind"
	// FieldCallerID holds the string denoting the caller_id field in the database.
	FieldCallerID = "caller_id"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResponseType holds the string denoting the response_type field in the database.
	FieldResponseType = "response_type"
	// FieldResponseJSON holds the string denoting the response_json field in the database.
	FieldResponseJSON = "response_json"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldResourceKind holds the string denoting the resource_kind field in the database.
	FieldResourceKind = "resource_kind"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the idempotencyrecord in the database.
	Table = "idempotency_records"
)

// Columns holds all SQL columns for idempotencyrecord fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCallerKind,
	FieldCallerID,
	FieldMethod,
	FieldRequestID,
	FieldRequestHash,
	FieldStatus,
	FieldResponseType,
	FieldResponseJSON,
	FieldErrorCode,
	FieldErrorMessage,
	FieldResourceKind,
	FieldResourceID,
	FieldEventID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultCallerKind holds the default value on creation for the "caller_kind" field.
	DefaultCallerKind string
	// DefaultCallerID holds the default value on creation for the "caller_id" field.
	DefaultCallerID string
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultRequestHash holds the default value on creation for the "request_hash" field.
	DefaultRequestHash string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultResponseType holds the default value on creation for the "response_type" field.
	DefaultResponseType string
	// DefaultResponseJSON holds the default value on creation for the "response_json" field.
	DefaultResponseJSON string
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultResourceKind holds the default value on creation for the "resource_kind" field.
	DefaultResourceKind string
	// DefaultResourceID holds the default value on creation for the "resource_id" field.
	DefaultResourceID string
	// DefaultEventID holds the default value on creation for the "event_id" field.
	DefaultEventID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the IdempotencyRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCallerKind orders the results by the caller_kind field.
func ByCallerKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallerKind, opts...).ToFunc()
}

// ByCallerID orders the results by the caller_id field.
func ByCallerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallerID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResponseType orders the results by the response_type field.
func ByResponseType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseType, opts...).ToFunc()
}

// ByResponseJSON orders the results by the response_json field.
func ByResponseJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseJSON, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByResourceKind orders the results by the resource_kind field.
func ByResourceKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceKind, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
